// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
	mock "github.com/stretchr/testify/mock"
)

// CrawlQuerier is an autogenerated mock type for the CrawlQuerier type
type CrawlQuerier struct {
	mock.Mock
}

type CrawlQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *CrawlQuerier) EXPECT() *CrawlQuerier_Expecter {
	return &CrawlQuerier_Expecter{mock: &_m.Mock}
}

// GetRecentCrawlerSearchNear provides a mock function with given fields: ctx, arg
func (_m *CrawlQuerier) GetRecentCrawlerSearchNear(ctx context.Context, arg sqlcgen.GetRecentCrawlerSearchNearParams) (sqlcgen.CrawlerSearch, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentCrawlerSearchNear")
	}

	var r0 sqlcgen.CrawlerSearch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetRecentCrawlerSearchNearParams) (sqlcgen.CrawlerSearch, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetRecentCrawlerSearchNearParams) sqlcgen.CrawlerSearch); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.CrawlerSearch)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.GetRecentCrawlerSearchNearParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CrawlQuerier_GetRecentCrawlerSearchNear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentCrawlerSearchNear'
type CrawlQuerier_GetRecentCrawlerSearchNear_Call struct {
	*mock.Call
}

// GetRecentCrawlerSearchNear is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.GetRecentCrawlerSearchNearParams
func (_e *CrawlQuerier_Expecter) GetRecentCrawlerSearchNear(ctx interface{}, arg interface{}) *CrawlQuerier_GetRecentCrawlerSearchNear_Call {
	return &CrawlQuerier_GetRecentCrawlerSearchNear_Call{Call: _e.mock.On("GetRecentCrawlerSearchNear", ctx, arg)}
}

func (_c *CrawlQuerier_GetRecentCrawlerSearchNear_Call) Run(run func(ctx context.Context, arg sqlcgen.GetRecentCrawlerSearchNearParams)) *CrawlQuerier_GetRecentCrawlerSearchNear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.GetRecentCrawlerSearchNearParams))
	})
	return _c
}

func (_c *CrawlQuerier_GetRecentCrawlerSearchNear_Call) Return(_a0 sqlcgen.CrawlerSearch, _a1 error) *CrawlQuerier_GetRecentCrawlerSearchNear_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CrawlQuerier_GetRecentCrawlerSearchNear_Call) RunAndReturn(run func(context.Context, sqlcgen.GetRecentCrawlerSearchNearParams) (sqlcgen.CrawlerSearch, error)) *CrawlQuerier_GetRecentCrawlerSearchNear_Call {
	_c.Call.Return(run)
	return _c
}

// NewCrawlQuerier creates a new instance of CrawlQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCrawlQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *CrawlQuerier {
	mock := &CrawlQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
