// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// CreateActivity provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateActivity(ctx context.Context, arg sqlcgen.CreateActivityParams) (sqlcgen.Activity, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivity")
	}

	var r0 sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateActivityParams) (sqlcgen.Activity, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateActivityParams) sqlcgen.Activity); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.Activity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateActivityParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivity'
type Querier_CreateActivity_Call struct {
	*mock.Call
}

// CreateActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.CreateActivityParams
func (_e *Querier_Expecter) CreateActivity(ctx interface{}, arg interface{}) *Querier_CreateActivity_Call {
	return &Querier_CreateActivity_Call{Call: _e.mock.On("CreateActivity", ctx, arg)}
}

func (_c *Querier_CreateActivity_Call) Run(run func(ctx context.Context, arg sqlcgen.CreateActivityParams)) *Querier_CreateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.CreateActivityParams))
	})
	return _c
}

func (_c *Querier_CreateActivity_Call) Return(_a0 sqlcgen.Activity, _a1 error) *Querier_CreateActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateActivity_Call) RunAndReturn(run func(context.Context, sqlcgen.CreateActivityParams) (sqlcgen.Activity, error)) *Querier_CreateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActivity provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteActivity(ctx context.Context, id string) (sqlcgen.Activity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActivity")
	}

	var r0 sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.Activity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.Activity); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlcgen.Activity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_DeleteActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActivity'
type Querier_DeleteActivity_Call struct {
	*mock.Call
}

// DeleteActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) DeleteActivity(ctx interface{}, id interface{}) *Querier_DeleteActivity_Call {
	return &Querier_DeleteActivity_Call{Call: _e.mock.On("DeleteActivity", ctx, id)}
}

func (_c *Querier_DeleteActivity_Call) Run(run func(ctx context.Context, id string)) *Querier_DeleteActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_DeleteActivity_Call) Return(_a0 sqlcgen.Activity, _a1 error) *Querier_DeleteActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_DeleteActivity_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.Activity, error)) *Querier_DeleteActivity_Call {
	_c.Call.Return(run)
	return _c
}

// FindActivitiesInBoundingBox provides a mock function with given fields: ctx, arg
func (_m *Querier) FindActivitiesInBoundingBox(ctx context.Context, arg sqlcgen.FindActivitiesInBoundingBoxParams) ([]sqlcgen.Activity, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindActivitiesInBoundingBox")
	}

	var r0 []sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.FindActivitiesInBoundingBoxParams) ([]sqlcgen.Activity, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.FindActivitiesInBoundingBoxParams) []sqlcgen.Activity); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.FindActivitiesInBoundingBoxParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_FindActivitiesInBoundingBox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActivitiesInBoundingBox'
type Querier_FindActivitiesInBoundingBox_Call struct {
	*mock.Call
}

// FindActivitiesInBoundingBox is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.FindActivitiesInBoundingBoxParams
func (_e *Querier_Expecter) FindActivitiesInBoundingBox(ctx interface{}, arg interface{}) *Querier_FindActivitiesInBoundingBox_Call {
	return &Querier_FindActivitiesInBoundingBox_Call{Call: _e.mock.On("FindActivitiesInBoundingBox", ctx, arg)}
}

func (_c *Querier_FindActivitiesInBoundingBox_Call) Run(run func(ctx context.Context, arg sqlcgen.FindActivitiesInBoundingBoxParams)) *Querier_FindActivitiesInBoundingBox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.FindActivitiesInBoundingBoxParams))
	})
	return _c
}

func (_c *Querier_FindActivitiesInBoundingBox_Call) Return(_a0 []sqlcgen.Activity, _a1 error) *Querier_FindActivitiesInBoundingBox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_FindActivitiesInBoundingBox_Call) RunAndReturn(run func(context.Context, sqlcgen.FindActivitiesInBoundingBoxParams) ([]sqlcgen.Activity, error)) *Querier_FindActivitiesInBoundingBox_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivitiesByIDs provides a mock function with given fields: ctx, ids
func (_m *Querier) GetActivitiesByIDs(ctx context.Context, ids []string) ([]sqlcgen.Activity, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetActivitiesByIDs")
	}

	var r0 []sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]sqlcgen.Activity, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []sqlcgen.Activity); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetActivitiesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivitiesByIDs'
type Querier_GetActivitiesByIDs_Call struct {
	*mock.Call
}

// GetActivitiesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *Querier_Expecter) GetActivitiesByIDs(ctx interface{}, ids interface{}) *Querier_GetActivitiesByIDs_Call {
	return &Querier_GetActivitiesByIDs_Call{Call: _e.mock.On("GetActivitiesByIDs", ctx, ids)}
}

func (_c *Querier_GetActivitiesByIDs_Call) Run(run func(ctx context.Context, ids []string)) *Querier_GetActivitiesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Querier_GetActivitiesByIDs_Call) Return(_a0 []sqlcgen.Activity, _a1 error) *Querier_GetActivitiesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetActivitiesByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]sqlcgen.Activity, error)) *Querier_GetActivitiesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivity provides a mock function with given fields: ctx, id
func (_m *Querier) GetActivity(ctx context.Context, id string) (sqlcgen.Activity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetActivity")
	}

	var r0 sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.Activity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.Activity); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlcgen.Activity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivity'
type Querier_GetActivity_Call struct {
	*mock.Call
}

// GetActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) GetActivity(ctx interface{}, id interface{}) *Querier_GetActivity_Call {
	return &Querier_GetActivity_Call{Call: _e.mock.On("GetActivity", ctx, id)}
}

func (_c *Querier_GetActivity_Call) Run(run func(ctx context.Context, id string)) *Querier_GetActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetActivity_Call) Return(_a0 sqlcgen.Activity, _a1 error) *Querier_GetActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetActivity_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.Activity, error)) *Querier_GetActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityBySourceExternalID provides a mock function with given fields: ctx, arg
func (_m *Querier) GetActivityBySourceExternalID(ctx context.Context, arg sqlcgen.GetActivityBySourceExternalIDParams) (sqlcgen.Activity, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityBySourceExternalID")
	}

	var r0 sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetActivityBySourceExternalIDParams) (sqlcgen.Activity, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetActivityBySourceExternalIDParams) sqlcgen.Activity); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.Activity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.GetActivityBySourceExternalIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetActivityBySourceExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityBySourceExternalID'
type Querier_GetActivityBySourceExternalID_Call struct {
	*mock.Call
}

// GetActivityBySourceExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.GetActivityBySourceExternalIDParams
func (_e *Querier_Expecter) GetActivityBySourceExternalID(ctx interface{}, arg interface{}) *Querier_GetActivityBySourceExternalID_Call {
	return &Querier_GetActivityBySourceExternalID_Call{Call: _e.mock.On("GetActivityBySourceExternalID", ctx, arg)}
}

func (_c *Querier_GetActivityBySourceExternalID_Call) Run(run func(ctx context.Context, arg sqlcgen.GetActivityBySourceExternalIDParams)) *Querier_GetActivityBySourceExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.GetActivityBySourceExternalIDParams))
	})
	return _c
}

func (_c *Querier_GetActivityBySourceExternalID_Call) Return(_a0 sqlcgen.Activity, _a1 error) *Querier_GetActivityBySourceExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetActivityBySourceExternalID_Call) RunAndReturn(run func(context.Context, sqlcgen.GetActivityBySourceExternalIDParams) (sqlcgen.Activity, error)) *Querier_GetActivityBySourceExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActivity provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateActivity(ctx context.Context, arg sqlcgen.UpdateActivityParams) (sqlcgen.Activity, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActivity")
	}

	var r0 sqlcgen.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateActivityParams) (sqlcgen.Activity, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateActivityParams) sqlcgen.Activity); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.Activity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.UpdateActivityParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActivity'
type Querier_UpdateActivity_Call struct {
	*mock.Call
}

// UpdateActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.UpdateActivityParams
func (_e *Querier_Expecter) UpdateActivity(ctx interface{}, arg interface{}) *Querier_UpdateActivity_Call {
	return &Querier_UpdateActivity_Call{Call: _e.mock.On("UpdateActivity", ctx, arg)}
}

func (_c *Querier_UpdateActivity_Call) Run(run func(ctx context.Context, arg sqlcgen.UpdateActivityParams)) *Querier_UpdateActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.UpdateActivityParams))
	})
	return _c
}

func (_c *Querier_UpdateActivity_Call) Return(_a0 sqlcgen.Activity, _a1 error) *Querier_UpdateActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateActivity_Call) RunAndReturn(run func(context.Context, sqlcgen.UpdateActivityParams) (sqlcgen.Activity, error)) *Querier_UpdateActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
