// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Crawler is an autogenerated mock type for the Crawler type
type Crawler struct {
	mock.Mock
}

type Crawler_Expecter struct {
	mock *mock.Mock
}

func (_m *Crawler) EXPECT() *Crawler_Expecter {
	return &Crawler_Expecter{mock: &_m.Mock}
}

// CrawlAndSaveActivities provides a mock function with given fields: ctx, latitude, longitude, radius
func (_m *Crawler) CrawlAndSaveActivities(ctx context.Context, latitude float64, longitude float64, radius float64) ([]string, error) {
	ret := _m.Called(ctx, latitude, longitude, radius)

	if len(ret) == 0 {
		panic("no return value specified for CrawlAndSaveActivities")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64) ([]string, error)); ok {
		return rf(ctx, latitude, longitude, radius)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64) []string); ok {
		r0 = rf(ctx, latitude, longitude, radius)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64) error); ok {
		r1 = rf(ctx, latitude, longitude, radius)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Crawler_CrawlAndSaveActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CrawlAndSaveActivities'
type Crawler_CrawlAndSaveActivities_Call struct {
	*mock.Call
}

// CrawlAndSaveActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - latitude float64
//   - longitude float64
//   - radius float64
func (_e *Crawler_Expecter) CrawlAndSaveActivities(ctx interface{}, latitude interface{}, longitude interface{}, radius interface{}) *Crawler_CrawlAndSaveActivities_Call {
	return &Crawler_CrawlAndSaveActivities_Call{Call: _e.mock.On("CrawlAndSaveActivities", ctx, latitude, longitude, radius)}
}

func (_c *Crawler_CrawlAndSaveActivities_Call) Run(run func(ctx context.Context, latitude float64, longitude float64, radius float64)) *Crawler_CrawlAndSaveActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64))
	})
	return _c
}

func (_c *Crawler_CrawlAndSaveActivities_Call) Return(_a0 []string, _a1 error) *Crawler_CrawlAndSaveActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Crawler_CrawlAndSaveActivities_Call) RunAndReturn(run func(context.Context, float64, float64, float64) ([]string, error)) *Crawler_CrawlAndSaveActivities_Call {
	_c.Call.Return(run)
	return _c
}

// NewCrawler creates a new instance of Crawler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCrawler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Crawler {
	mock := &Crawler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
