// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ai "github.com/juanobrach/zig-zag/go-be/internal/ai"

	mock "github.com/stretchr/testify/mock"
)

// VectorFinder is an autogenerated mock type for the VectorFinder type
type VectorFinder struct {
	mock.Mock
}

type VectorFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *VectorFinder) EXPECT() *VectorFinder_Expecter {
	return &VectorFinder_Expecter{mock: &_m.Mock}
}

// FindSimilarActivities provides a mock function with given fields: ctx, prompt, k
func (_m *VectorFinder) FindSimilarActivities(ctx context.Context, prompt string, k int) ([]ai.SimilarActivityResult, error) {
	ret := _m.Called(ctx, prompt, k)

	if len(ret) == 0 {
		panic("no return value specified for FindSimilarActivities")
	}

	var r0 []ai.SimilarActivityResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]ai.SimilarActivityResult, error)); ok {
		return rf(ctx, prompt, k)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []ai.SimilarActivityResult); ok {
		r0 = rf(ctx, prompt, k)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ai.SimilarActivityResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, prompt, k)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VectorFinder_FindSimilarActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSimilarActivities'
type VectorFinder_FindSimilarActivities_Call struct {
	*mock.Call
}

// FindSimilarActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - k int
func (_e *VectorFinder_Expecter) FindSimilarActivities(ctx interface{}, prompt interface{}, k interface{}) *VectorFinder_FindSimilarActivities_Call {
	return &VectorFinder_FindSimilarActivities_Call{Call: _e.mock.On("FindSimilarActivities", ctx, prompt, k)}
}

func (_c *VectorFinder_FindSimilarActivities_Call) Run(run func(ctx context.Context, prompt string, k int)) *VectorFinder_FindSimilarActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *VectorFinder_FindSimilarActivities_Call) Return(_a0 []ai.SimilarActivityResult, _a1 error) *VectorFinder_FindSimilarActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VectorFinder_FindSimilarActivities_Call) RunAndReturn(run func(context.Context, string, int) ([]ai.SimilarActivityResult, error)) *VectorFinder_FindSimilarActivities_Call {
	_c.Call.Return(run)
	return _c
}

// NewVectorFinder creates a new instance of VectorFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVectorFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *VectorFinder {
	mock := &VectorFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
