// A.1/A.2 regression evidence over the RECORDED v5 runs: re-validate and
// re-assemble the model's recorded answers under the current contract
// (editorial structure + verified anaphora). No provider calls and no prompt
// change. This is a counterfactual over frozen output, not a gate result and
// not a new semantic measurement.
//   node spikes/rw4-atom-labelling-2026-10-06/counterfactual-a1-a2.cjs
'use strict';
const fs = require('fs');
const path = require('path');
const { fold } = require('./atom-labelling.cjs');
const { replayRecorded } = require('./replay-recorded.cjs');
const { scoreSource, scoreRegression } = require('./score.cjs');
const { SOURCES } = require('./units.cjs');

const HERE = __dirname;
const MAIN = path.join(HERE, 'runs/v5-batched-relabel-gemini');
const REG = path.join(HERE, 'runs/v5-regression-gemini');

function recordedRow(dir, input, run) {
  return JSON.parse(fs.readFileSync(path.join(dir, 'results.ENTITY_ROLES.json'), 'utf8')).find((r) => r.input === input && r.run === run);
}

// Which atoms made a name mandatory (ITINERARY_STOP provenance).
const stopAtoms = (segments, name) =>
  segments.flatMap((s) => s.members.filter((m) => m.role === 'ITINERARY_STOP' && fold(m.sourceName) === fold(name)).flatMap((m) => m.provenance.filter((p) => p.role === 'ITINERARY_STOP').map((p) => p.atomId)));

const rows = [];
for (const [dir, inputs, runs] of [
  [MAIN, ['SOB_UNIT', 'AG_UNIT'], 5],
  [REG, ['RW3_EV3', 'ROUTE_EXPERIENCE'], 3],
]) {
  for (const input of inputs) {
    for (let run = 1; run <= runs; run++) {
      const rec = recordedRow(dir, input, run);
      const x = replayRecorded(dir, input, run);
      const segments = x.segments;
      const score = segments ? (SOURCES[input] ? scoreSource(SOURCES[input].sourceId, segments, x.atoms, x.final.labels) : scoreRegression(input, segments)) : null;
      const anaphors = x.final
        ? [...x.final.labels.values()].flatMap((l) => l.entities.filter((e) => e.anaphor).map((e) => `${l.atomId} "${e.anaphor.surfaceForm}"→${e.anaphor.mentionAtomId} ${e.anaphor.status}${e.anaphor.antecedent ? ` (${e.anaphor.antecedent.sourceName})` : ''}`))
        : [];
      rows.push({
        input,
        run,
        recordedOutcome: rec.validity === 'INVALID_RUN' ? 'INVALID_RUN' : rec.outcome,
        recordedFinalIssues: [...(rec.malformed ?? []), ...(rec.spanIssues ?? [])].map((i) => `${i.code}:${i.atomId}`),
        replayOutcome: x.outcome,
        replayFirstPassIssues: x.relabel ? x.relabel.firstPassIssues : [],
        replayFinalIssues: (x.final ?? x.first)?.issues.map((i) => `${i.code}:${i.atomId}`) ?? [],
        nonEditorialAtoms: x.atoms.filter((a) => !a.editorial).length,
        navigationBlocks: x.structure.blocks.map((b) => `${b.firstAtomId}..${b.lastAtomId}(${b.atomCount})`),
        recordedVerdicts: rec.verdicts?.map((v) => `${v.segment} ${v.mandatoryRecall}`) ?? [],
        replayVerdicts: score?.verdicts.map((v) => `${v.segment} ${v.mandatoryRecall}${v.success ? '' : ` [${v.reasons.join(',')}]`}`) ?? [],
        replaySegments: segments?.length ?? null,
        sanTelmoStopAtoms: segments ? stopAtoms(segments, 'San Telmo') : null,
        recordedRouteAreaPromoted: rec.routeAreaPromoted ?? [],
        replayRouteAreaPromoted: score?.routeAreaPromoted ?? [],
        anaphors,
      });
    }
  }
}

const out = [
  '# A.1/A.2 counterfactual over recorded v5 runs (no provider calls)',
  '',
  'Generated by `counterfactual-a1-a2.cjs`. The recorded model answers of',
  '`v5-batched-relabel-gemini` and `v5-regression-gemini` are re-validated',
  'and re-assembled under the current contract: link-only navigation blocks',
  'are NON_EDITORIAL (A.1) and `mentionAtomId` anaphora is verified against',
  "the cited atom's own entities (A.2). Labels the model gave to atoms now",
  'outside editorial content are dropped, because those atoms would never be',
  'presented. Not a gate result; semantic labels are unchanged by construction.',
  '',
  '| Unit | Run | Recorded outcome | Replay outcome | Replay 1st-pass issues | Replay final issues | Non-editorial atoms | Recorded recall | Replay recall | San Telmo stop atoms (replay) | Route/area promoted (recorded → replay) | Anaphors (replay) |',
  '|---|---|---|---|---|---|---|---|---|---|---|---|',
  ...rows.map((r) =>
    [
      r.input,
      r.run,
      `${r.recordedOutcome}${r.recordedFinalIssues.length ? ` (${r.recordedFinalIssues.join(', ')})` : ''}`,
      r.replayOutcome,
      r.replayFirstPassIssues.join(', ') || '–',
      r.replayFinalIssues.join(', ') || 'none',
      r.nonEditorialAtoms,
      r.recordedVerdicts.join(', ') || '–',
      r.replayVerdicts.join(', ') || '–',
      r.sanTelmoStopAtoms ? r.sanTelmoStopAtoms.join(', ') || 'none' : '–',
      `${r.recordedRouteAreaPromoted.join('/') || 'none'} → ${r.replayRouteAreaPromoted.join('/') || 'none'}`,
      r.anaphors.join('; ') || '–',
    ].join(' | '),
  ).map((l) => `| ${l} |`),
  '',
];
fs.writeFileSync(path.join(HERE, 'runs/counterfactual-a1-a2.md'), out.join('\n'));
fs.writeFileSync(path.join(HERE, 'runs/counterfactual-a1-a2.json'), JSON.stringify(rows, null, 2) + '\n');
console.log(out.join('\n'));
