// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO "activity" (
  "id", "name", "description", "type", "difficulty", "duration", "price", "maxGroupSize",
  "latitude", "longitude", "location", "address", "sourceId", "externalId",
  "rating", "ratingCount", "formattedAddress", "phoneNumber", "website", "businessStatus",
  "priceLevel", "photos", "openingHours", "metadata", "knownActivityTypeName", "createdAt", "updatedAt"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
  $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, now(), now()
) RETURNING id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding
`

type CreateActivityParams struct {
	ID                    string      `json:"id"`
	Name                  string      `json:"name"`
	Description           *string     `json:"description"`
	Type                  *string     `json:"type"`
	Difficulty            *Difficulty `json:"difficulty"`
	Duration              *float64    `json:"duration"`
	Price                 *float64    `json:"price"`
	MaxGroupSize          *int32      `json:"maxGroupSize"`
	Latitude              *float64    `json:"latitude"`
	Longitude             *float64    `json:"longitude"`
	Location              []byte      `json:"location"`
	Address               *string     `json:"address"`
	SourceId              *string     `json:"sourceId"`
	ExternalId            *string     `json:"externalId"`
	Rating                *float64    `json:"rating"`
	RatingCount           *int32      `json:"ratingCount"`
	FormattedAddress      *string     `json:"formattedAddress"`
	PhoneNumber           *string     `json:"phoneNumber"`
	Website               *string     `json:"website"`
	BusinessStatus        *string     `json:"businessStatus"`
	PriceLevel            *int32      `json:"priceLevel"`
	Photos                []byte      `json:"photos"`
	OpeningHours          []byte      `json:"openingHours"`
	Metadata              []byte      `json:"metadata"`
	KnownActivityTypeName *string     `json:"knownActivityTypeName"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Difficulty,
		arg.Duration,
		arg.Price,
		arg.MaxGroupSize,
		arg.Latitude,
		arg.Longitude,
		arg.Location,
		arg.Address,
		arg.SourceId,
		arg.ExternalId,
		arg.Rating,
		arg.RatingCount,
		arg.FormattedAddress,
		arg.PhoneNumber,
		arg.Website,
		arg.BusinessStatus,
		arg.PriceLevel,
		arg.Photos,
		arg.OpeningHours,
		arg.Metadata,
		arg.KnownActivityTypeName,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.Duration,
		&i.Price,
		&i.MaxGroupSize,
		&i.Latitude,
		&i.Longitude,
		&i.Location,
		&i.Address,
		&i.SourceId,
		&i.ExternalId,
		&i.Rating,
		&i.RatingCount,
		&i.FormattedAddress,
		&i.PhoneNumber,
		&i.Website,
		&i.BusinessStatus,
		&i.PriceLevel,
		&i.Photos,
		&i.OpeningHours,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KnownActivityTypeName,
		&i.Embedding,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :one
DELETE FROM "activity" WHERE "id" = $1 RETURNING id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding
`

func (q *Queries) DeleteActivity(ctx context.Context, id string) (Activity, error) {
	row := q.db.QueryRow(ctx, deleteActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.Duration,
		&i.Price,
		&i.MaxGroupSize,
		&i.Latitude,
		&i.Longitude,
		&i.Location,
		&i.Address,
		&i.SourceId,
		&i.ExternalId,
		&i.Rating,
		&i.RatingCount,
		&i.FormattedAddress,
		&i.PhoneNumber,
		&i.Website,
		&i.BusinessStatus,
		&i.PriceLevel,
		&i.Photos,
		&i.OpeningHours,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KnownActivityTypeName,
		&i.Embedding,
	)
	return i, err
}

const findActivitiesInBoundingBox = `-- name: FindActivitiesInBoundingBox :many
SELECT id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding FROM "activity"
WHERE "latitude" >= $1 AND "latitude" <= $2 AND "longitude" >= $3 AND "longitude" <= $4
`

type FindActivitiesInBoundingBoxParams struct {
	Latitude    *float64 `json:"latitude"`
	Latitude_2  *float64 `json:"latitude_2"`
	Longitude   *float64 `json:"longitude"`
	Longitude_2 *float64 `json:"longitude_2"`
}

func (q *Queries) FindActivitiesInBoundingBox(ctx context.Context, arg FindActivitiesInBoundingBoxParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, findActivitiesInBoundingBox,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Difficulty,
			&i.Duration,
			&i.Price,
			&i.MaxGroupSize,
			&i.Latitude,
			&i.Longitude,
			&i.Location,
			&i.Address,
			&i.SourceId,
			&i.ExternalId,
			&i.Rating,
			&i.RatingCount,
			&i.FormattedAddress,
			&i.PhoneNumber,
			&i.Website,
			&i.BusinessStatus,
			&i.PriceLevel,
			&i.Photos,
			&i.OpeningHours,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KnownActivityTypeName,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivitiesByIDs = `-- name: GetActivitiesByIDs :many
SELECT id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding FROM "activity" WHERE "id" = ANY($1::text[])
`

func (q *Queries) GetActivitiesByIDs(ctx context.Context, ids []string) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getActivitiesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Difficulty,
			&i.Duration,
			&i.Price,
			&i.MaxGroupSize,
			&i.Latitude,
			&i.Longitude,
			&i.Location,
			&i.Address,
			&i.SourceId,
			&i.ExternalId,
			&i.Rating,
			&i.RatingCount,
			&i.FormattedAddress,
			&i.PhoneNumber,
			&i.Website,
			&i.BusinessStatus,
			&i.PriceLevel,
			&i.Photos,
			&i.OpeningHours,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KnownActivityTypeName,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivity = `-- name: GetActivity :one

SELECT id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding FROM "activity" WHERE "id" = $1
`

// Queries backing internal/activities, mirroring ActivitiesService's Prisma
// calls in be/src/modules/activities/services/activities.service.ts.
func (q *Queries) GetActivity(ctx context.Context, id string) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.Duration,
		&i.Price,
		&i.MaxGroupSize,
		&i.Latitude,
		&i.Longitude,
		&i.Location,
		&i.Address,
		&i.SourceId,
		&i.ExternalId,
		&i.Rating,
		&i.RatingCount,
		&i.FormattedAddress,
		&i.PhoneNumber,
		&i.Website,
		&i.BusinessStatus,
		&i.PriceLevel,
		&i.Photos,
		&i.OpeningHours,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KnownActivityTypeName,
		&i.Embedding,
	)
	return i, err
}

const getActivityBySourceExternalID = `-- name: GetActivityBySourceExternalID :one
SELECT id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding FROM "activity" WHERE "sourceId" = $1 AND "externalId" = $2
`

type GetActivityBySourceExternalIDParams struct {
	SourceId   *string `json:"sourceId"`
	ExternalId *string `json:"externalId"`
}

func (q *Queries) GetActivityBySourceExternalID(ctx context.Context, arg GetActivityBySourceExternalIDParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityBySourceExternalID, arg.SourceId, arg.ExternalId)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.Duration,
		&i.Price,
		&i.MaxGroupSize,
		&i.Latitude,
		&i.Longitude,
		&i.Location,
		&i.Address,
		&i.SourceId,
		&i.ExternalId,
		&i.Rating,
		&i.RatingCount,
		&i.FormattedAddress,
		&i.PhoneNumber,
		&i.Website,
		&i.BusinessStatus,
		&i.PriceLevel,
		&i.Photos,
		&i.OpeningHours,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KnownActivityTypeName,
		&i.Embedding,
	)
	return i, err
}

const getRecentCrawlerSearchNear = `-- name: GetRecentCrawlerSearchNear :one
SELECT id, latitude, longitude, "deviceToken", "createdAt", "updatedAt" FROM "crawler_search"
WHERE "latitude" >= $1 AND "latitude" <= $2 AND "longitude" >= $3 AND "longitude" <= $4
  AND "createdAt" >= $5
LIMIT 1
`

type GetRecentCrawlerSearchNearParams struct {
	Latitude    float64          `json:"latitude"`
	Latitude_2  float64          `json:"latitude_2"`
	Longitude   float64          `json:"longitude"`
	Longitude_2 float64          `json:"longitude_2"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

// Mirrors HybridSearchService.shouldTriggerCrawling's findFirst — note this
// table is read-only in the current Nest codebase (nothing ever writes a
// CrawlerSearch row), so this lookup always misses and background crawling
// triggers on every hybrid search. That looks like an incomplete feature
// upstream, not something to silently "fix" here — ported as-is.
func (q *Queries) GetRecentCrawlerSearchNear(ctx context.Context, arg GetRecentCrawlerSearchNearParams) (CrawlerSearch, error) {
	row := q.db.QueryRow(ctx, getRecentCrawlerSearchNear,
		arg.Latitude,
		arg.Latitude_2,
		arg.Longitude,
		arg.Longitude_2,
		arg.CreatedAt,
	)
	var i CrawlerSearch
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.DeviceToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE "activity" SET
  "name" = $2, "description" = $3, "type" = $4, "difficulty" = $5, "duration" = $6,
  "price" = $7, "maxGroupSize" = $8, "latitude" = $9, "longitude" = $10, "location" = $11,
  "address" = $12, "sourceId" = $13, "externalId" = $14, "rating" = $15, "ratingCount" = $16,
  "formattedAddress" = $17, "phoneNumber" = $18, "website" = $19, "businessStatus" = $20,
  "priceLevel" = $21, "photos" = $22, "openingHours" = $23, "metadata" = $24,
  "knownActivityTypeName" = $25, "updatedAt" = now()
WHERE "id" = $1
RETURNING id, name, description, type, difficulty, duration, price, "maxGroupSize", latitude, longitude, location, address, "sourceId", "externalId", rating, "ratingCount", "formattedAddress", "phoneNumber", website, "businessStatus", "priceLevel", photos, "openingHours", metadata, "createdAt", "updatedAt", "knownActivityTypeName", embedding
`

type UpdateActivityParams struct {
	ID                    string      `json:"id"`
	Name                  string      `json:"name"`
	Description           *string     `json:"description"`
	Type                  *string     `json:"type"`
	Difficulty            *Difficulty `json:"difficulty"`
	Duration              *float64    `json:"duration"`
	Price                 *float64    `json:"price"`
	MaxGroupSize          *int32      `json:"maxGroupSize"`
	Latitude              *float64    `json:"latitude"`
	Longitude             *float64    `json:"longitude"`
	Location              []byte      `json:"location"`
	Address               *string     `json:"address"`
	SourceId              *string     `json:"sourceId"`
	ExternalId            *string     `json:"externalId"`
	Rating                *float64    `json:"rating"`
	RatingCount           *int32      `json:"ratingCount"`
	FormattedAddress      *string     `json:"formattedAddress"`
	PhoneNumber           *string     `json:"phoneNumber"`
	Website               *string     `json:"website"`
	BusinessStatus        *string     `json:"businessStatus"`
	PriceLevel            *int32      `json:"priceLevel"`
	Photos                []byte      `json:"photos"`
	OpeningHours          []byte      `json:"openingHours"`
	Metadata              []byte      `json:"metadata"`
	KnownActivityTypeName *string     `json:"knownActivityTypeName"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Difficulty,
		arg.Duration,
		arg.Price,
		arg.MaxGroupSize,
		arg.Latitude,
		arg.Longitude,
		arg.Location,
		arg.Address,
		arg.SourceId,
		arg.ExternalId,
		arg.Rating,
		arg.RatingCount,
		arg.FormattedAddress,
		arg.PhoneNumber,
		arg.Website,
		arg.BusinessStatus,
		arg.PriceLevel,
		arg.Photos,
		arg.OpeningHours,
		arg.Metadata,
		arg.KnownActivityTypeName,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Difficulty,
		&i.Duration,
		&i.Price,
		&i.MaxGroupSize,
		&i.Latitude,
		&i.Longitude,
		&i.Location,
		&i.Address,
		&i.SourceId,
		&i.ExternalId,
		&i.Rating,
		&i.RatingCount,
		&i.FormattedAddress,
		&i.PhoneNumber,
		&i.Website,
		&i.BusinessStatus,
		&i.PriceLevel,
		&i.Photos,
		&i.OpeningHours,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KnownActivityTypeName,
		&i.Embedding,
	)
	return i, err
}
