// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserRefreshTokenHash = `-- name: ClearUserRefreshTokenHash :exec
UPDATE "user" SET "refreshTokenHash" = NULL, "updatedAt" = now() WHERE "id" = $1
`

func (q *Queries) ClearUserRefreshTokenHash(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearUserRefreshTokenHash, id)
	return err
}

const consumeEmailLoginCode = `-- name: ConsumeEmailLoginCode :exec
UPDATE "email_login_code" SET "consumedAt" = now() WHERE "id" = $1
`

func (q *Queries) ConsumeEmailLoginCode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeEmailLoginCode, id)
	return err
}

const createEmailLoginCode = `-- name: CreateEmailLoginCode :one
INSERT INTO "email_login_code" ("id", "email", "codeHash", "expiresAt", "createdAt")
VALUES ($1, $2, $3, $4, now())
RETURNING id, email, "codeHash", "expiresAt", attempts, "consumedAt", "createdAt"
`

type CreateEmailLoginCodeParams struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	CodeHash  string           `json:"codeHash"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreateEmailLoginCode(ctx context.Context, arg CreateEmailLoginCodeParams) (EmailLoginCode, error) {
	row := q.db.QueryRow(ctx, createEmailLoginCode,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i EmailLoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" ("id", "email", "name", "avatarUrl", "provider", "providerId", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, email, name, "avatarUrl", provider, "providerId", "refreshTokenHash", "createdAt", "updatedAt"
`

type CreateUserParams struct {
	ID         string       `json:"id"`
	Email      string       `json:"email"`
	Name       *string      `json:"name"`
	AvatarUrl  *string      `json:"avatarUrl"`
	Provider   AuthProvider `json:"provider"`
	ProviderId string       `json:"providerId"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderId,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderId,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastEmailLoginCode = `-- name: GetLastEmailLoginCode :one
SELECT id, email, "codeHash", "expiresAt", attempts, "consumedAt", "createdAt" FROM "email_login_code" WHERE "email" = $1 ORDER BY "createdAt" DESC LIMIT 1
`

func (q *Queries) GetLastEmailLoginCode(ctx context.Context, email string) (EmailLoginCode, error) {
	row := q.db.QueryRow(ctx, getLastEmailLoginCode, email)
	var i EmailLoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingEmailLoginCode = `-- name: GetPendingEmailLoginCode :one
SELECT id, email, "codeHash", "expiresAt", attempts, "consumedAt", "createdAt" FROM "email_login_code" WHERE "email" = $1 AND "consumedAt" IS NULL ORDER BY "createdAt" DESC LIMIT 1
`

func (q *Queries) GetPendingEmailLoginCode(ctx context.Context, email string) (EmailLoginCode, error) {
	row := q.db.QueryRow(ctx, getPendingEmailLoginCode, email)
	var i EmailLoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, "avatarUrl", provider, "providerId", "refreshTokenHash", "createdAt", "updatedAt" FROM "user" WHERE "id" = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderId,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one

SELECT id, email, name, "avatarUrl", provider, "providerId", "refreshTokenHash", "createdAt", "updatedAt" FROM "user" WHERE "provider" = $1 AND "providerId" = $2
`

type GetUserByProviderIDParams struct {
	Provider   AuthProvider `json:"provider"`
	ProviderId string       `json:"providerId"`
}

// Queries backing internal/auth, mirroring be/src/modules/auth/services/{auth,email-otp}.service.ts.
func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.Provider, arg.ProviderId)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderId,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementEmailLoginCodeAttempts = `-- name: IncrementEmailLoginCodeAttempts :exec
UPDATE "email_login_code" SET "attempts" = "attempts" + 1 WHERE "id" = $1
`

func (q *Queries) IncrementEmailLoginCodeAttempts(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementEmailLoginCodeAttempts, id)
	return err
}

const setUserRefreshTokenHash = `-- name: SetUserRefreshTokenHash :exec
UPDATE "user" SET "refreshTokenHash" = $2, "updatedAt" = now() WHERE "id" = $1
`

type SetUserRefreshTokenHashParams struct {
	ID               string  `json:"id"`
	RefreshTokenHash *string `json:"refreshTokenHash"`
}

func (q *Queries) SetUserRefreshTokenHash(ctx context.Context, arg SetUserRefreshTokenHashParams) error {
	_, err := q.db.Exec(ctx, setUserRefreshTokenHash, arg.ID, arg.RefreshTokenHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE "user" SET "name" = $2, "avatarUrl" = $3, "updatedAt" = now()
WHERE "id" = $1
RETURNING id, email, name, "avatarUrl", provider, "providerId", "refreshTokenHash", "createdAt", "updatedAt"
`

type UpdateUserProfileParams struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	AvatarUrl *string `json:"avatarUrl"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderId,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
