// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cli.sql

package sqlcgen

import (
	"context"
)

const listActivitiesWithID = `-- name: ListActivitiesWithID :many

SELECT "id", "name", "metadata" FROM "activity"
`

type ListActivitiesWithIDRow struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Metadata []byte `json:"metadata"`
}

// Queries backing cmd/cli's maintenance commands, mirroring the Prisma
// calls in be/src/commands/scripts/commands/*.command.ts.
func (q *Queries) ListActivitiesWithID(ctx context.Context) ([]ListActivitiesWithIDRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesWithID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesWithIDRow
	for rows.Next() {
		var i ListActivitiesWithIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Metadata); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesWithoutPhotos = `-- name: ListActivitiesWithoutPhotos :many
SELECT "id", "name", "type", "description" FROM "activity"
WHERE "photos" IS NULL OR "photos"::text = 'null' OR "photos"::text = '[]'
`

type ListActivitiesWithoutPhotosRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Type        *string `json:"type"`
	Description *string `json:"description"`
}

func (q *Queries) ListActivitiesWithoutPhotos(ctx context.Context) ([]ListActivitiesWithoutPhotosRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesWithoutPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesWithoutPhotosRow
	for rows.Next() {
		var i ListActivitiesWithoutPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToursWithoutCoverImage = `-- name: ListToursWithoutCoverImage :many
SELECT "id", "name" FROM "tour" WHERE "coverImage" IS NULL OR "coverImage" = ''
`

type ListToursWithoutCoverImageRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListToursWithoutCoverImage(ctx context.Context) ([]ListToursWithoutCoverImageRow, error) {
	rows, err := q.db.Query(ctx, listToursWithoutCoverImage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToursWithoutCoverImageRow
	for rows.Next() {
		var i ListToursWithoutCoverImageRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivityPhotos = `-- name: SetActivityPhotos :exec
UPDATE "activity" SET "photos" = $2, "updatedAt" = now() WHERE "id" = $1
`

type SetActivityPhotosParams struct {
	ID     string `json:"id"`
	Photos []byte `json:"photos"`
}

func (q *Queries) SetActivityPhotos(ctx context.Context, arg SetActivityPhotosParams) error {
	_, err := q.db.Exec(ctx, setActivityPhotos, arg.ID, arg.Photos)
	return err
}
