// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const findSimilarActivities = `-- name: FindSimilarActivities :many
SELECT "id", "name", "embedding" <=> $1 AS distance
FROM "activity"
WHERE "embedding" IS NOT NULL
ORDER BY "embedding" <=> $1
LIMIT $2
`

type FindSimilarActivitiesParams struct {
	Embedding *pgvector.Vector `json:"embedding"`
	Limit     int32            `json:"limit"`
}

type FindSimilarActivitiesRow struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Distance interface{} `json:"distance"`
}

// Mirrors VectorStoreService.findSimilarActivities (be/src/shared/ai/services/vector-store.service.ts):
// cosine distance via the <=> operator, ordered nearest-first.
func (q *Queries) FindSimilarActivities(ctx context.Context, arg FindSimilarActivitiesParams) ([]FindSimilarActivitiesRow, error) {
	rows, err := q.db.Query(ctx, findSimilarActivities, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarActivitiesRow
	for rows.Next() {
		var i FindSimilarActivitiesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Distance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityByID = `-- name: GetActivityByID :one

SELECT "id", "name", "metadata", "photos", "embedding"
FROM "activity"
WHERE "id" = $1
`

type GetActivityByIDRow struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Metadata  []byte           `json:"metadata"`
	Photos    []byte           `json:"photos"`
	Embedding *pgvector.Vector `json:"embedding"`
}

// Foundation-phase queries: exist to validate sqlc's type mapping for JSON,
// native array, and pgvector columns against the real schema before any
// domain module builds its full query set on top of it.
func (q *Queries) GetActivityByID(ctx context.Context, id string) (GetActivityByIDRow, error) {
	row := q.db.QueryRow(ctx, getActivityByID, id)
	var i GetActivityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.Photos,
		&i.Embedding,
	)
	return i, err
}

const getTourByID = `-- name: GetTourByID :one
SELECT "id", "name", "startDates", "categories", "metadata"
FROM "tour"
WHERE "id" = $1
`

type GetTourByIDRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	StartDates []pgtype.Timestamp `json:"startDates"`
	Categories []string           `json:"categories"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) GetTourByID(ctx context.Context, id string) (GetTourByIDRow, error) {
	row := q.db.QueryRow(ctx, getTourByID, id)
	var i GetTourByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDates,
		&i.Categories,
		&i.Metadata,
	)
	return i, err
}
