// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AuthProvider string

const (
	AuthProviderGOOGLE AuthProvider = "GOOGLE"
	AuthProviderAPPLE  AuthProvider = "APPLE"
	AuthProviderEMAIL  AuthProvider = "EMAIL"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"AuthProvider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type Difficulty string

const (
	DifficultyEASY   Difficulty = "EASY"
	DifficultyMEDIUM Difficulty = "MEDIUM"
	DifficultyHARD   Difficulty = "HARD"
)

func (e *Difficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Difficulty(s)
	case string:
		*e = Difficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for Difficulty: %T", src)
	}
	return nil
}

type NullDifficulty struct {
	Difficulty Difficulty `json:"Difficulty"`
	Valid      bool       `json:"valid"` // Valid is true if Difficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.Difficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Difficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Difficulty), nil
}

type RelationType string

const (
	RelationTypeSEQUENTIAL    RelationType = "SEQUENTIAL"
	RelationTypeSIMILAR       RelationType = "SIMILAR"
	RelationTypeCOMPLEMENTARY RelationType = "COMPLEMENTARY"
)

func (e *RelationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RelationType(s)
	case string:
		*e = RelationType(s)
	default:
		return fmt.Errorf("unsupported scan type for RelationType: %T", src)
	}
	return nil
}

type NullRelationType struct {
	RelationType RelationType `json:"RelationType"`
	Valid        bool         `json:"valid"` // Valid is true if RelationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationType) Scan(value interface{}) error {
	if value == nil {
		ns.RelationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelationType), nil
}

type Activity struct {
	ID                    string           `json:"id"`
	Name                  string           `json:"name"`
	Description           *string          `json:"description"`
	Type                  *string          `json:"type"`
	Difficulty            *Difficulty      `json:"difficulty"`
	Duration              *float64         `json:"duration"`
	Price                 *float64         `json:"price"`
	MaxGroupSize          *int32           `json:"maxGroupSize"`
	Latitude              *float64         `json:"latitude"`
	Longitude             *float64         `json:"longitude"`
	Location              []byte           `json:"location"`
	Address               *string          `json:"address"`
	SourceId              *string          `json:"sourceId"`
	ExternalId            *string          `json:"externalId"`
	Rating                *float64         `json:"rating"`
	RatingCount           *int32           `json:"ratingCount"`
	FormattedAddress      *string          `json:"formattedAddress"`
	PhoneNumber           *string          `json:"phoneNumber"`
	Website               *string          `json:"website"`
	BusinessStatus        *string          `json:"businessStatus"`
	PriceLevel            *int32           `json:"priceLevel"`
	Photos                []byte           `json:"photos"`
	OpeningHours          []byte           `json:"openingHours"`
	Metadata              []byte           `json:"metadata"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
	KnownActivityTypeName *string          `json:"knownActivityTypeName"`
	Embedding             *pgvector.Vector `json:"embedding"`
}

type ActivityRelationship struct {
	ID                     string           `json:"id"`
	SourceActivityId       string           `json:"sourceActivityId"`
	TargetActivityId       string           `json:"targetActivityId"`
	RelationType           RelationType     `json:"relationType"`
	CompatibilityScore     int32            `json:"compatibilityScore"`
	TimeCompatibilityScore int32            `json:"timeCompatibilityScore"`
	DistanceScore          int32            `json:"distanceScore"`
	VarietyScore           int32            `json:"varietyScore"`
	TimeGapRecommended     *int32           `json:"timeGapRecommended"`
	Reasoning              *string          `json:"reasoning"`
	Metadata               []byte           `json:"metadata"`
	CreatedAt              pgtype.Timestamp `json:"createdAt"`
	UpdatedAt              pgtype.Timestamp `json:"updatedAt"`
}

type CrawlerSearch struct {
	ID          string           `json:"id"`
	Latitude    float64          `json:"latitude"`
	Longitude   float64          `json:"longitude"`
	DeviceToken *string          `json:"deviceToken"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type EmailLoginCode struct {
	ID         string           `json:"id"`
	Email      string           `json:"email"`
	CodeHash   string           `json:"codeHash"`
	ExpiresAt  pgtype.Timestamp `json:"expiresAt"`
	Attempts   int32            `json:"attempts"`
	ConsumedAt pgtype.Timestamp `json:"consumedAt"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
}

type KnownActivityType struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Icon        *string          `json:"icon"`
	Category    *string          `json:"category"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type Source struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	BaseUrl   *string          `json:"baseUrl"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type Tour struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	Description          *string            `json:"description"`
	OwnerId              *string            `json:"ownerId"`
	Price                *float64           `json:"price"`
	Duration             *float64           `json:"duration"`
	MaxGroupSize         *int32             `json:"maxGroupSize"`
	StartDates           []pgtype.Timestamp `json:"startDates"`
	TotalDays            *int32             `json:"totalDays"`
	TotalDistance        *float64           `json:"totalDistance"`
	EstimatedBudget      *float64           `json:"estimatedBudget"`
	RecommendedGroupSize *int32             `json:"recommendedGroupSize"`
	CoverImage           *string            `json:"coverImage"`
	Prompt               *string            `json:"prompt"`
	Query                *string            `json:"query"`
	Categories           []string           `json:"categories"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamp   `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp   `json:"updatedAt"`
}

type TourActivity struct {
	ID                string           `json:"id"`
	TourId            string           `json:"tourId"`
	ActivityId        *string          `json:"activityId"`
	StartTime         pgtype.Timestamp `json:"startTime"`
	Duration          *float64         `json:"duration"`
	Notes             *string          `json:"notes"`
	DayNumber         *int32           `json:"dayNumber"`
	TravelTimeToNext  *float64         `json:"travelTimeToNext"`
	DistanceToNext    *float64         `json:"distanceToNext"`
	Order             int32            `json:"order"`
	ActivityName      *string          `json:"activityName"`
	ActivityType      *string          `json:"activityType"`
	ActivityLatitude  *float64         `json:"activityLatitude"`
	ActivityLongitude *float64         `json:"activityLongitude"`
	ActivityData      []byte           `json:"activityData"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID               string           `json:"id"`
	Email            string           `json:"email"`
	Name             *string          `json:"name"`
	AvatarUrl        *string          `json:"avatarUrl"`
	Provider         AuthProvider     `json:"provider"`
	ProviderId       string           `json:"providerId"`
	RefreshTokenHash *string          `json:"refreshTokenHash"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
}
