// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: places.sql

package sqlcgen

import (
	"context"
)

const createKnownActivityType = `-- name: CreateKnownActivityType :one
INSERT INTO "known_activity_types" ("id", "name", "icon", "description", "category", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, name, description, icon, category, "createdAt", "updatedAt"
`

type CreateKnownActivityTypeParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Icon        *string `json:"icon"`
	Description *string `json:"description"`
	Category    *string `json:"category"`
}

func (q *Queries) CreateKnownActivityType(ctx context.Context, arg CreateKnownActivityTypeParams) (KnownActivityType, error) {
	row := q.db.QueryRow(ctx, createKnownActivityType,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Description,
		arg.Category,
	)
	var i KnownActivityType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO "source" ("id", "name", "type", "baseUrl", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, name, type, "baseUrl", "createdAt", "updatedAt"
`

type CreateSourceParams struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Type    string  `json:"type"`
	BaseUrl *string `json:"baseUrl"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityBySourceAndExternalID = `-- name: GetActivityBySourceAndExternalID :one
SELECT "id" FROM "activity" WHERE "sourceId" = $1 AND "externalId" = $2
`

type GetActivityBySourceAndExternalIDParams struct {
	SourceId   *string `json:"sourceId"`
	ExternalId *string `json:"externalId"`
}

func (q *Queries) GetActivityBySourceAndExternalID(ctx context.Context, arg GetActivityBySourceAndExternalIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getActivityBySourceAndExternalID, arg.SourceId, arg.ExternalId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getKnownActivityTypeByName = `-- name: GetKnownActivityTypeByName :one

SELECT id, name, description, icon, category, "createdAt", "updatedAt" FROM "known_activity_types" WHERE "name" = $1
`

// Queries backing internal/places, mirroring GooglePlacesService's Prisma
// calls in be/src/modules/integrations/google-places/google-places.service.ts.
func (q *Queries) GetKnownActivityTypeByName(ctx context.Context, name string) (KnownActivityType, error) {
	row := q.db.QueryRow(ctx, getKnownActivityTypeByName, name)
	var i KnownActivityType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByName = `-- name: GetSourceByName :one
SELECT id, name, type, "baseUrl", "createdAt", "updatedAt" FROM "source" WHERE "name" = $1
`

func (q *Queries) GetSourceByName(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByName, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKnownActivityType = `-- name: UpdateKnownActivityType :exec
UPDATE "known_activity_types" SET "icon" = $2, "description" = $3, "category" = $4, "updatedAt" = now()
WHERE "id" = $1
`

type UpdateKnownActivityTypeParams struct {
	ID          string  `json:"id"`
	Icon        *string `json:"icon"`
	Description *string `json:"description"`
	Category    *string `json:"category"`
}

func (q *Queries) UpdateKnownActivityType(ctx context.Context, arg UpdateKnownActivityTypeParams) error {
	_, err := q.db.Exec(ctx, updateKnownActivityType,
		arg.ID,
		arg.Icon,
		arg.Description,
		arg.Category,
	)
	return err
}
