// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tours.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countToursByOwner = `-- name: CountToursByOwner :one
SELECT count(*) FROM "tour" WHERE "ownerId" = $1 AND ($2::text IS NULL OR $2::text = ANY("categories"))
`

type CountToursByOwnerParams struct {
	OwnerId  *string `json:"ownerId"`
	Category *string `json:"category"`
}

func (q *Queries) CountToursByOwner(ctx context.Context, arg CountToursByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countToursByOwner, arg.OwnerId, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTour = `-- name: CreateTour :one

INSERT INTO "tour" (
  "id", "ownerId", "name", "description", "price", "duration", "maxGroupSize",
  "startDates", "totalDays", "totalDistance", "estimatedBudget", "recommendedGroupSize",
  "prompt", "query", "categories", "metadata", "createdAt", "updatedAt"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now(), now()
) RETURNING id, name, description, "ownerId", price, duration, "maxGroupSize", "startDates", "totalDays", "totalDistance", "estimatedBudget", "recommendedGroupSize", "coverImage", prompt, query, categories, metadata, "createdAt", "updatedAt"
`

type CreateTourParams struct {
	ID                   string             `json:"id"`
	OwnerId              *string            `json:"ownerId"`
	Name                 string             `json:"name"`
	Description          *string            `json:"description"`
	Price                *float64           `json:"price"`
	Duration             *float64           `json:"duration"`
	MaxGroupSize         *int32             `json:"maxGroupSize"`
	StartDates           []pgtype.Timestamp `json:"startDates"`
	TotalDays            *int32             `json:"totalDays"`
	TotalDistance        *float64           `json:"totalDistance"`
	EstimatedBudget      *float64           `json:"estimatedBudget"`
	RecommendedGroupSize *int32             `json:"recommendedGroupSize"`
	Prompt               *string            `json:"prompt"`
	Query                *string            `json:"query"`
	Categories           []string           `json:"categories"`
	Metadata             []byte             `json:"metadata"`
}

// Queries backing internal/tours, mirroring ToursService/TourActivityGenerationService's
// Prisma calls in be/src/modules/tours/services/*.ts.
func (q *Queries) CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error) {
	row := q.db.QueryRow(ctx, createTour,
		arg.ID,
		arg.OwnerId,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Duration,
		arg.MaxGroupSize,
		arg.StartDates,
		arg.TotalDays,
		arg.TotalDistance,
		arg.EstimatedBudget,
		arg.RecommendedGroupSize,
		arg.Prompt,
		arg.Query,
		arg.Categories,
		arg.Metadata,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerId,
		&i.Price,
		&i.Duration,
		&i.MaxGroupSize,
		&i.StartDates,
		&i.TotalDays,
		&i.TotalDistance,
		&i.EstimatedBudget,
		&i.RecommendedGroupSize,
		&i.CoverImage,
		&i.Prompt,
		&i.Query,
		&i.Categories,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTourActivity = `-- name: CreateTourActivity :exec
INSERT INTO "tour_activity" (
  "id", "tourId", "activityId", "activityName", "activityType", "activityLatitude",
  "activityLongitude", "activityData", "duration", "startTime", "notes", "dayNumber",
  "travelTimeToNext", "distanceToNext", "order", "createdAt", "updatedAt"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now(), now()
)
`

type CreateTourActivityParams struct {
	ID                string           `json:"id"`
	TourId            string           `json:"tourId"`
	ActivityId        *string          `json:"activityId"`
	ActivityName      *string          `json:"activityName"`
	ActivityType      *string          `json:"activityType"`
	ActivityLatitude  *float64         `json:"activityLatitude"`
	ActivityLongitude *float64         `json:"activityLongitude"`
	ActivityData      []byte           `json:"activityData"`
	Duration          *float64         `json:"duration"`
	StartTime         pgtype.Timestamp `json:"startTime"`
	Notes             *string          `json:"notes"`
	DayNumber         *int32           `json:"dayNumber"`
	TravelTimeToNext  *float64         `json:"travelTimeToNext"`
	DistanceToNext    *float64         `json:"distanceToNext"`
	Order             int32            `json:"order"`
}

func (q *Queries) CreateTourActivity(ctx context.Context, arg CreateTourActivityParams) error {
	_, err := q.db.Exec(ctx, createTourActivity,
		arg.ID,
		arg.TourId,
		arg.ActivityId,
		arg.ActivityName,
		arg.ActivityType,
		arg.ActivityLatitude,
		arg.ActivityLongitude,
		arg.ActivityData,
		arg.Duration,
		arg.StartTime,
		arg.Notes,
		arg.DayNumber,
		arg.TravelTimeToNext,
		arg.DistanceToNext,
		arg.Order,
	)
	return err
}

const deleteTour = `-- name: DeleteTour :exec
DELETE FROM "tour" WHERE "id" = $1
`

// TourActivity rows cascade-delete via the schema's onDelete: Cascade — no
// separate tour_activity delete needed first (unlike Nest's explicit
// deleteMany, which predates relying on the DB constraint).
func (q *Queries) DeleteTour(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTour, id)
	return err
}

const deleteTourActivities = `-- name: DeleteTourActivities :exec
DELETE FROM "tour_activity" WHERE "tourId" = $1
`

func (q *Queries) DeleteTourActivities(ctx context.Context, tourid string) error {
	_, err := q.db.Exec(ctx, deleteTourActivities, tourid)
	return err
}

const getActivityLatLngByIDs = `-- name: GetActivityLatLngByIDs :many
SELECT "id", "latitude", "longitude" FROM "activity" WHERE "id" = ANY($1::text[])
`

type GetActivityLatLngByIDsRow struct {
	ID        string   `json:"id"`
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
}

func (q *Queries) GetActivityLatLngByIDs(ctx context.Context, ids []string) ([]GetActivityLatLngByIDsRow, error) {
	rows, err := q.db.Query(ctx, getActivityLatLngByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivityLatLngByIDsRow
	for rows.Next() {
		var i GetActivityLatLngByIDsRow
		if err := rows.Scan(&i.ID, &i.Latitude, &i.Longitude); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTour = `-- name: GetTour :one
SELECT id, name, description, "ownerId", price, duration, "maxGroupSize", "startDates", "totalDays", "totalDistance", "estimatedBudget", "recommendedGroupSize", "coverImage", prompt, query, categories, metadata, "createdAt", "updatedAt" FROM "tour" WHERE "id" = $1
`

func (q *Queries) GetTour(ctx context.Context, id string) (Tour, error) {
	row := q.db.QueryRow(ctx, getTour, id)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerId,
		&i.Price,
		&i.Duration,
		&i.MaxGroupSize,
		&i.StartDates,
		&i.TotalDays,
		&i.TotalDistance,
		&i.EstimatedBudget,
		&i.RecommendedGroupSize,
		&i.CoverImage,
		&i.Prompt,
		&i.Query,
		&i.Categories,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTourActivities = `-- name: GetTourActivities :many
SELECT id, "tourId", "activityId", "startTime", duration, notes, "dayNumber", "travelTimeToNext", "distanceToNext", "order", "activityName", "activityType", "activityLatitude", "activityLongitude", "activityData", "createdAt", "updatedAt" FROM "tour_activity" WHERE "tourId" = $1 ORDER BY "order" ASC
`

func (q *Queries) GetTourActivities(ctx context.Context, tourid string) ([]TourActivity, error) {
	rows, err := q.db.Query(ctx, getTourActivities, tourid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TourActivity
	for rows.Next() {
		var i TourActivity
		if err := rows.Scan(
			&i.ID,
			&i.TourId,
			&i.ActivityId,
			&i.StartTime,
			&i.Duration,
			&i.Notes,
			&i.DayNumber,
			&i.TravelTimeToNext,
			&i.DistanceToNext,
			&i.Order,
			&i.ActivityName,
			&i.ActivityType,
			&i.ActivityLatitude,
			&i.ActivityLongitude,
			&i.ActivityData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTourOwnerID = `-- name: GetTourOwnerID :one
SELECT "ownerId" FROM "tour" WHERE "id" = $1
`

func (q *Queries) GetTourOwnerID(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getTourOwnerID, id)
	var ownerId *string
	err := row.Scan(&ownerId)
	return ownerId, err
}

const listToursByOwner = `-- name: ListToursByOwner :many
SELECT id, name, description, "ownerId", price, duration, "maxGroupSize", "startDates", "totalDays", "totalDistance", "estimatedBudget", "recommendedGroupSize", "coverImage", prompt, query, categories, metadata, "createdAt", "updatedAt" FROM "tour"
WHERE "ownerId" = $1 AND ($4::text IS NULL OR $4::text = ANY("categories"))
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListToursByOwnerParams struct {
	OwnerId  *string `json:"ownerId"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	Category *string `json:"category"`
}

func (q *Queries) ListToursByOwner(ctx context.Context, arg ListToursByOwnerParams) ([]Tour, error) {
	rows, err := q.db.Query(ctx, listToursByOwner,
		arg.OwnerId,
		arg.Limit,
		arg.Offset,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tour
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerId,
			&i.Price,
			&i.Duration,
			&i.MaxGroupSize,
			&i.StartDates,
			&i.TotalDays,
			&i.TotalDistance,
			&i.EstimatedBudget,
			&i.RecommendedGroupSize,
			&i.CoverImage,
			&i.Prompt,
			&i.Query,
			&i.Categories,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToursNearCategory = `-- name: ListToursNearCategory :many
SELECT DISTINCT t.id, t.name, t.description, t."ownerId", t.price, t.duration, t."maxGroupSize", t."startDates", t."totalDays", t."totalDistance", t."estimatedBudget", t."recommendedGroupSize", t."coverImage", t.prompt, t.query, t.categories, t.metadata, t."createdAt", t."updatedAt" FROM "tour" t
LEFT JOIN "tour_activity" ta ON ta."tourId" = t."id"
LEFT JOIN "activity" a ON a."id" = ta."activityId"
WHERE (
  (ta."activityLatitude" BETWEEN $1 AND $2 AND ta."activityLongitude" BETWEEN $3 AND $4)
  OR (a."latitude" BETWEEN $1 AND $2 AND a."longitude" BETWEEN $3 AND $4)
) AND (t."name" ILIKE $5 OR t."description" ILIKE $5)
LIMIT 10
`

type ListToursNearCategoryParams struct {
	ActivityLatitude    *float64 `json:"activityLatitude"`
	ActivityLatitude_2  *float64 `json:"activityLatitude_2"`
	ActivityLongitude   *float64 `json:"activityLongitude"`
	ActivityLongitude_2 *float64 `json:"activityLongitude_2"`
	Name                string   `json:"name"`
}

// Mirrors getNearbyTours' bounding-box + name/description ILIKE search.
func (q *Queries) ListToursNearCategory(ctx context.Context, arg ListToursNearCategoryParams) ([]Tour, error) {
	rows, err := q.db.Query(ctx, listToursNearCategory,
		arg.ActivityLatitude,
		arg.ActivityLatitude_2,
		arg.ActivityLongitude,
		arg.ActivityLongitude_2,
		arg.Name,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tour
	for rows.Next() {
		var i Tour
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerId,
			&i.Price,
			&i.Duration,
			&i.MaxGroupSize,
			&i.StartDates,
			&i.TotalDays,
			&i.TotalDistance,
			&i.EstimatedBudget,
			&i.RecommendedGroupSize,
			&i.CoverImage,
			&i.Prompt,
			&i.Query,
			&i.Categories,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTour = `-- name: UpdateTour :one
UPDATE "tour" SET
  "name" = $2, "description" = $3, "price" = $4, "duration" = $5, "maxGroupSize" = $6,
  "startDates" = $7, "totalDays" = $8, "totalDistance" = $9, "estimatedBudget" = $10,
  "recommendedGroupSize" = $11, "prompt" = $12, "query" = $13, "categories" = $14,
  "metadata" = $15, "updatedAt" = now()
WHERE "id" = $1
RETURNING id, name, description, "ownerId", price, duration, "maxGroupSize", "startDates", "totalDays", "totalDistance", "estimatedBudget", "recommendedGroupSize", "coverImage", prompt, query, categories, metadata, "createdAt", "updatedAt"
`

type UpdateTourParams struct {
	ID                   string             `json:"id"`
	Name                 string             `json:"name"`
	Description          *string            `json:"description"`
	Price                *float64           `json:"price"`
	Duration             *float64           `json:"duration"`
	MaxGroupSize         *int32             `json:"maxGroupSize"`
	StartDates           []pgtype.Timestamp `json:"startDates"`
	TotalDays            *int32             `json:"totalDays"`
	TotalDistance        *float64           `json:"totalDistance"`
	EstimatedBudget      *float64           `json:"estimatedBudget"`
	RecommendedGroupSize *int32             `json:"recommendedGroupSize"`
	Prompt               *string            `json:"prompt"`
	Query                *string            `json:"query"`
	Categories           []string           `json:"categories"`
	Metadata             []byte             `json:"metadata"`
}

func (q *Queries) UpdateTour(ctx context.Context, arg UpdateTourParams) (Tour, error) {
	row := q.db.QueryRow(ctx, updateTour,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Duration,
		arg.MaxGroupSize,
		arg.StartDates,
		arg.TotalDays,
		arg.TotalDistance,
		arg.EstimatedBudget,
		arg.RecommendedGroupSize,
		arg.Prompt,
		arg.Query,
		arg.Categories,
		arg.Metadata,
	)
	var i Tour
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerId,
		&i.Price,
		&i.Duration,
		&i.MaxGroupSize,
		&i.StartDates,
		&i.TotalDays,
		&i.TotalDistance,
		&i.EstimatedBudget,
		&i.RecommendedGroupSize,
		&i.CoverImage,
		&i.Prompt,
		&i.Query,
		&i.Categories,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTourCoverImage = `-- name: UpdateTourCoverImage :exec
UPDATE "tour" SET "coverImage" = $2, "updatedAt" = now() WHERE "id" = $1
`

type UpdateTourCoverImageParams struct {
	ID         string  `json:"id"`
	CoverImage *string `json:"coverImage"`
}

func (q *Queries) UpdateTourCoverImage(ctx context.Context, arg UpdateTourCoverImageParams) error {
	_, err := q.db.Exec(ctx, updateTourCoverImage, arg.ID, arg.CoverImage)
	return err
}

const updateTourMetadata = `-- name: UpdateTourMetadata :exec
UPDATE "tour" SET "metadata" = $2, "updatedAt" = now() WHERE "id" = $1
`

type UpdateTourMetadataParams struct {
	ID       string `json:"id"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) UpdateTourMetadata(ctx context.Context, arg UpdateTourMetadataParams) error {
	_, err := q.db.Exec(ctx, updateTourMetadata, arg.ID, arg.Metadata)
	return err
}
