// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vectorstore.sql

package sqlcgen

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const countEmbeddedActivities = `-- name: CountEmbeddedActivities :one
SELECT count(*) FROM "activity" WHERE "embedding" IS NOT NULL
`

func (q *Queries) CountEmbeddedActivities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmbeddedActivities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findSimilarActivitiesFull = `-- name: FindSimilarActivitiesFull :many
SELECT "id", "name", "description", "type", "metadata",
       "embedding" <=> $1 AS distance
FROM "activity"
WHERE "embedding" IS NOT NULL
ORDER BY "embedding" <=> $1
LIMIT $2
`

type FindSimilarActivitiesFullParams struct {
	Embedding *pgvector.Vector `json:"embedding"`
	Limit     int32            `json:"limit"`
}

type FindSimilarActivitiesFullRow struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Type        *string     `json:"type"`
	Metadata    []byte      `json:"metadata"`
	Distance    interface{} `json:"distance"`
}

func (q *Queries) FindSimilarActivitiesFull(ctx context.Context, arg FindSimilarActivitiesFullParams) ([]FindSimilarActivitiesFullRow, error) {
	rows, err := q.db.Query(ctx, findSimilarActivitiesFull, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSimilarActivitiesFullRow
	for rows.Next() {
		var i FindSimilarActivitiesFullRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Metadata,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesWithMetadata = `-- name: ListActivitiesWithMetadata :many
SELECT "id", "name", "description", "type", "metadata"
FROM "activity"
WHERE "metadata" IS NOT NULL
`

type ListActivitiesWithMetadataRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Type        *string `json:"type"`
	Metadata    []byte  `json:"metadata"`
}

// Feeds rebuildVectorStore: every activity that has enrichment metadata to embed from.
func (q *Queries) ListActivitiesWithMetadata(ctx context.Context) ([]ListActivitiesWithMetadataRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesWithMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesWithMetadataRow
	for rows.Next() {
		var i ListActivitiesWithMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetVectorStore = `-- name: ResetVectorStore :exec
UPDATE "activity" SET "embedding" = NULL
`

// Clears every stored embedding without touching Activity rows themselves.
func (q *Queries) ResetVectorStore(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetVectorStore)
	return err
}

const updateActivityEmbedding = `-- name: UpdateActivityEmbedding :exec

UPDATE "activity" SET "embedding" = $2 WHERE "id" = $1
`

type UpdateActivityEmbeddingParams struct {
	ID        string           `json:"id"`
	Embedding *pgvector.Vector `json:"embedding"`
}

// Queries backing internal/ai's VectorStore, mirroring
// be/src/shared/ai/services/vector-store.service.ts.
func (q *Queries) UpdateActivityEmbedding(ctx context.Context, arg UpdateActivityEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateActivityEmbedding, arg.ID, arg.Embedding)
	return err
}
