// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Embedder is an autogenerated mock type for the Embedder type
type Embedder struct {
	mock.Mock
}

type Embedder_Expecter struct {
	mock *mock.Mock
}

func (_m *Embedder) EXPECT() *Embedder_Expecter {
	return &Embedder_Expecter{mock: &_m.Mock}
}

// EmbedDocuments provides a mock function with given fields: ctx, texts
func (_m *Embedder) EmbedDocuments(ctx context.Context, texts []string) ([][]float64, error) {
	ret := _m.Called(ctx, texts)

	if len(ret) == 0 {
		panic("no return value specified for EmbedDocuments")
	}

	var r0 [][]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([][]float64, error)); ok {
		return rf(ctx, texts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) [][]float64); ok {
		r0 = rf(ctx, texts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, texts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Embedder_EmbedDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedDocuments'
type Embedder_EmbedDocuments_Call struct {
	*mock.Call
}

// EmbedDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - texts []string
func (_e *Embedder_Expecter) EmbedDocuments(ctx interface{}, texts interface{}) *Embedder_EmbedDocuments_Call {
	return &Embedder_EmbedDocuments_Call{Call: _e.mock.On("EmbedDocuments", ctx, texts)}
}

func (_c *Embedder_EmbedDocuments_Call) Run(run func(ctx context.Context, texts []string)) *Embedder_EmbedDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Embedder_EmbedDocuments_Call) Return(_a0 [][]float64, _a1 error) *Embedder_EmbedDocuments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Embedder_EmbedDocuments_Call) RunAndReturn(run func(context.Context, []string) ([][]float64, error)) *Embedder_EmbedDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedQuery provides a mock function with given fields: ctx, text
func (_m *Embedder) EmbedQuery(ctx context.Context, text string) ([]float64, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for EmbedQuery")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float64, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float64); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Embedder_EmbedQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedQuery'
type Embedder_EmbedQuery_Call struct {
	*mock.Call
}

// EmbedQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *Embedder_Expecter) EmbedQuery(ctx interface{}, text interface{}) *Embedder_EmbedQuery_Call {
	return &Embedder_EmbedQuery_Call{Call: _e.mock.On("EmbedQuery", ctx, text)}
}

func (_c *Embedder_EmbedQuery_Call) Run(run func(ctx context.Context, text string)) *Embedder_EmbedQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Embedder_EmbedQuery_Call) Return(_a0 []float64, _a1 error) *Embedder_EmbedQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Embedder_EmbedQuery_Call) RunAndReturn(run func(context.Context, string) ([]float64, error)) *Embedder_EmbedQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmbedder creates a new instance of Embedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Embedder {
	mock := &Embedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
