// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	openai "github.com/sashabaranov/go-openai"
	mock "github.com/stretchr/testify/mock"
)

// ImageClient is an autogenerated mock type for the ImageClient type
type ImageClient struct {
	mock.Mock
}

type ImageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageClient) EXPECT() *ImageClient_Expecter {
	return &ImageClient_Expecter{mock: &_m.Mock}
}

// CreateImage provides a mock function with given fields: ctx, request
func (_m *ImageClient) CreateImage(ctx context.Context, request openai.ImageRequest) (openai.ImageResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateImage")
	}

	var r0 openai.ImageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, openai.ImageRequest) (openai.ImageResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, openai.ImageRequest) openai.ImageResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(openai.ImageResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, openai.ImageRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageClient_CreateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImage'
type ImageClient_CreateImage_Call struct {
	*mock.Call
}

// CreateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - request openai.ImageRequest
func (_e *ImageClient_Expecter) CreateImage(ctx interface{}, request interface{}) *ImageClient_CreateImage_Call {
	return &ImageClient_CreateImage_Call{Call: _e.mock.On("CreateImage", ctx, request)}
}

func (_c *ImageClient_CreateImage_Call) Run(run func(ctx context.Context, request openai.ImageRequest)) *ImageClient_CreateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(openai.ImageRequest))
	})
	return _c
}

func (_c *ImageClient_CreateImage_Call) Return(_a0 openai.ImageResponse, _a1 error) *ImageClient_CreateImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageClient_CreateImage_Call) RunAndReturn(run func(context.Context, openai.ImageRequest) (openai.ImageResponse, error)) *ImageClient_CreateImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewImageClient creates a new instance of ImageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageClient {
	mock := &ImageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
