// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChatModel is an autogenerated mock type for the ChatModel type
type ChatModel struct {
	mock.Mock
}

type ChatModel_Expecter struct {
	mock *mock.Mock
}

func (_m *ChatModel) EXPECT() *ChatModel_Expecter {
	return &ChatModel_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function with given fields: ctx, systemPrompt, userPrompt
func (_m *ChatModel) Chat(ctx context.Context, systemPrompt string, userPrompt string) (string, error) {
	ret := _m.Called(ctx, systemPrompt, userPrompt)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, systemPrompt, userPrompt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, systemPrompt, userPrompt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, systemPrompt, userPrompt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatModel_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type ChatModel_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - systemPrompt string
//   - userPrompt string
func (_e *ChatModel_Expecter) Chat(ctx interface{}, systemPrompt interface{}, userPrompt interface{}) *ChatModel_Chat_Call {
	return &ChatModel_Chat_Call{Call: _e.mock.On("Chat", ctx, systemPrompt, userPrompt)}
}

func (_c *ChatModel_Chat_Call) Run(run func(ctx context.Context, systemPrompt string, userPrompt string)) *ChatModel_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ChatModel_Chat_Call) Return(_a0 string, _a1 error) *ChatModel_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatModel_Chat_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *ChatModel_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// NewChatModel creates a new instance of ChatModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatModel {
	mock := &ChatModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
