// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
	mock "github.com/stretchr/testify/mock"
)

// VectorQuerier is an autogenerated mock type for the VectorQuerier type
type VectorQuerier struct {
	mock.Mock
}

type VectorQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *VectorQuerier) EXPECT() *VectorQuerier_Expecter {
	return &VectorQuerier_Expecter{mock: &_m.Mock}
}

// CountEmbeddedActivities provides a mock function with given fields: ctx
func (_m *VectorQuerier) CountEmbeddedActivities(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountEmbeddedActivities")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VectorQuerier_CountEmbeddedActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountEmbeddedActivities'
type VectorQuerier_CountEmbeddedActivities_Call struct {
	*mock.Call
}

// CountEmbeddedActivities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VectorQuerier_Expecter) CountEmbeddedActivities(ctx interface{}) *VectorQuerier_CountEmbeddedActivities_Call {
	return &VectorQuerier_CountEmbeddedActivities_Call{Call: _e.mock.On("CountEmbeddedActivities", ctx)}
}

func (_c *VectorQuerier_CountEmbeddedActivities_Call) Run(run func(ctx context.Context)) *VectorQuerier_CountEmbeddedActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *VectorQuerier_CountEmbeddedActivities_Call) Return(_a0 int64, _a1 error) *VectorQuerier_CountEmbeddedActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VectorQuerier_CountEmbeddedActivities_Call) RunAndReturn(run func(context.Context) (int64, error)) *VectorQuerier_CountEmbeddedActivities_Call {
	_c.Call.Return(run)
	return _c
}

// FindSimilarActivitiesFull provides a mock function with given fields: ctx, arg
func (_m *VectorQuerier) FindSimilarActivitiesFull(ctx context.Context, arg sqlcgen.FindSimilarActivitiesFullParams) ([]sqlcgen.FindSimilarActivitiesFullRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindSimilarActivitiesFull")
	}

	var r0 []sqlcgen.FindSimilarActivitiesFullRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.FindSimilarActivitiesFullParams) ([]sqlcgen.FindSimilarActivitiesFullRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.FindSimilarActivitiesFullParams) []sqlcgen.FindSimilarActivitiesFullRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.FindSimilarActivitiesFullRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.FindSimilarActivitiesFullParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VectorQuerier_FindSimilarActivitiesFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSimilarActivitiesFull'
type VectorQuerier_FindSimilarActivitiesFull_Call struct {
	*mock.Call
}

// FindSimilarActivitiesFull is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.FindSimilarActivitiesFullParams
func (_e *VectorQuerier_Expecter) FindSimilarActivitiesFull(ctx interface{}, arg interface{}) *VectorQuerier_FindSimilarActivitiesFull_Call {
	return &VectorQuerier_FindSimilarActivitiesFull_Call{Call: _e.mock.On("FindSimilarActivitiesFull", ctx, arg)}
}

func (_c *VectorQuerier_FindSimilarActivitiesFull_Call) Run(run func(ctx context.Context, arg sqlcgen.FindSimilarActivitiesFullParams)) *VectorQuerier_FindSimilarActivitiesFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.FindSimilarActivitiesFullParams))
	})
	return _c
}

func (_c *VectorQuerier_FindSimilarActivitiesFull_Call) Return(_a0 []sqlcgen.FindSimilarActivitiesFullRow, _a1 error) *VectorQuerier_FindSimilarActivitiesFull_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VectorQuerier_FindSimilarActivitiesFull_Call) RunAndReturn(run func(context.Context, sqlcgen.FindSimilarActivitiesFullParams) ([]sqlcgen.FindSimilarActivitiesFullRow, error)) *VectorQuerier_FindSimilarActivitiesFull_Call {
	_c.Call.Return(run)
	return _c
}

// ListActivitiesWithMetadata provides a mock function with given fields: ctx
func (_m *VectorQuerier) ListActivitiesWithMetadata(ctx context.Context) ([]sqlcgen.ListActivitiesWithMetadataRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActivitiesWithMetadata")
	}

	var r0 []sqlcgen.ListActivitiesWithMetadataRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]sqlcgen.ListActivitiesWithMetadataRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []sqlcgen.ListActivitiesWithMetadataRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.ListActivitiesWithMetadataRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VectorQuerier_ListActivitiesWithMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActivitiesWithMetadata'
type VectorQuerier_ListActivitiesWithMetadata_Call struct {
	*mock.Call
}

// ListActivitiesWithMetadata is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VectorQuerier_Expecter) ListActivitiesWithMetadata(ctx interface{}) *VectorQuerier_ListActivitiesWithMetadata_Call {
	return &VectorQuerier_ListActivitiesWithMetadata_Call{Call: _e.mock.On("ListActivitiesWithMetadata", ctx)}
}

func (_c *VectorQuerier_ListActivitiesWithMetadata_Call) Run(run func(ctx context.Context)) *VectorQuerier_ListActivitiesWithMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *VectorQuerier_ListActivitiesWithMetadata_Call) Return(_a0 []sqlcgen.ListActivitiesWithMetadataRow, _a1 error) *VectorQuerier_ListActivitiesWithMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VectorQuerier_ListActivitiesWithMetadata_Call) RunAndReturn(run func(context.Context) ([]sqlcgen.ListActivitiesWithMetadataRow, error)) *VectorQuerier_ListActivitiesWithMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ResetVectorStore provides a mock function with given fields: ctx
func (_m *VectorQuerier) ResetVectorStore(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetVectorStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VectorQuerier_ResetVectorStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetVectorStore'
type VectorQuerier_ResetVectorStore_Call struct {
	*mock.Call
}

// ResetVectorStore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VectorQuerier_Expecter) ResetVectorStore(ctx interface{}) *VectorQuerier_ResetVectorStore_Call {
	return &VectorQuerier_ResetVectorStore_Call{Call: _e.mock.On("ResetVectorStore", ctx)}
}

func (_c *VectorQuerier_ResetVectorStore_Call) Run(run func(ctx context.Context)) *VectorQuerier_ResetVectorStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *VectorQuerier_ResetVectorStore_Call) Return(_a0 error) *VectorQuerier_ResetVectorStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VectorQuerier_ResetVectorStore_Call) RunAndReturn(run func(context.Context) error) *VectorQuerier_ResetVectorStore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActivityEmbedding provides a mock function with given fields: ctx, arg
func (_m *VectorQuerier) UpdateActivityEmbedding(ctx context.Context, arg sqlcgen.UpdateActivityEmbeddingParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActivityEmbedding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateActivityEmbeddingParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VectorQuerier_UpdateActivityEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActivityEmbedding'
type VectorQuerier_UpdateActivityEmbedding_Call struct {
	*mock.Call
}

// UpdateActivityEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.UpdateActivityEmbeddingParams
func (_e *VectorQuerier_Expecter) UpdateActivityEmbedding(ctx interface{}, arg interface{}) *VectorQuerier_UpdateActivityEmbedding_Call {
	return &VectorQuerier_UpdateActivityEmbedding_Call{Call: _e.mock.On("UpdateActivityEmbedding", ctx, arg)}
}

func (_c *VectorQuerier_UpdateActivityEmbedding_Call) Run(run func(ctx context.Context, arg sqlcgen.UpdateActivityEmbeddingParams)) *VectorQuerier_UpdateActivityEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.UpdateActivityEmbeddingParams))
	})
	return _c
}

func (_c *VectorQuerier_UpdateActivityEmbedding_Call) Return(_a0 error) *VectorQuerier_UpdateActivityEmbedding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VectorQuerier_UpdateActivityEmbedding_Call) RunAndReturn(run func(context.Context, sqlcgen.UpdateActivityEmbeddingParams) error) *VectorQuerier_UpdateActivityEmbedding_Call {
	_c.Call.Return(run)
	return _c
}

// NewVectorQuerier creates a new instance of VectorQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVectorQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *VectorQuerier {
	mock := &VectorQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
