// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

type Mailer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailer) EXPECT() *Mailer_Expecter {
	return &Mailer_Expecter{mock: &_m.Mock}
}

// SendLoginCode provides a mock function with given fields: ctx, email, code
func (_m *Mailer) SendLoginCode(ctx context.Context, email string, code string) error {
	ret := _m.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for SendLoginCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_SendLoginCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendLoginCode'
type Mailer_SendLoginCode_Call struct {
	*mock.Call
}

// SendLoginCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
func (_e *Mailer_Expecter) SendLoginCode(ctx interface{}, email interface{}, code interface{}) *Mailer_SendLoginCode_Call {
	return &Mailer_SendLoginCode_Call{Call: _e.mock.On("SendLoginCode", ctx, email, code)}
}

func (_c *Mailer_SendLoginCode_Call) Run(run func(ctx context.Context, email string, code string)) *Mailer_SendLoginCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mailer_SendLoginCode_Call) Return(_a0 error) *Mailer_SendLoginCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_SendLoginCode_Call) RunAndReturn(run func(context.Context, string, string) error) *Mailer_SendLoginCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
