// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/juanobrach/zig-zag/go-be/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// AppleVerifier is an autogenerated mock type for the AppleVerifier type
type AppleVerifier struct {
	mock.Mock
}

type AppleVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *AppleVerifier) EXPECT() *AppleVerifier_Expecter {
	return &AppleVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, identityToken
func (_m *AppleVerifier) Verify(ctx context.Context, identityToken string) (auth.VerifiedAppleUser, error) {
	ret := _m.Called(ctx, identityToken)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 auth.VerifiedAppleUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (auth.VerifiedAppleUser, error)); ok {
		return rf(ctx, identityToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) auth.VerifiedAppleUser); ok {
		r0 = rf(ctx, identityToken)
	} else {
		r0 = ret.Get(0).(auth.VerifiedAppleUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, identityToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppleVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type AppleVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - identityToken string
func (_e *AppleVerifier_Expecter) Verify(ctx interface{}, identityToken interface{}) *AppleVerifier_Verify_Call {
	return &AppleVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, identityToken)}
}

func (_c *AppleVerifier_Verify_Call) Run(run func(ctx context.Context, identityToken string)) *AppleVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AppleVerifier_Verify_Call) Return(_a0 auth.VerifiedAppleUser, _a1 error) *AppleVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppleVerifier_Verify_Call) RunAndReturn(run func(context.Context, string) (auth.VerifiedAppleUser, error)) *AppleVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppleVerifier creates a new instance of AppleVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppleVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppleVerifier {
	mock := &AppleVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
