// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// ClearUserRefreshTokenHash provides a mock function with given fields: ctx, id
func (_m *Querier) ClearUserRefreshTokenHash(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearUserRefreshTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_ClearUserRefreshTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearUserRefreshTokenHash'
type Querier_ClearUserRefreshTokenHash_Call struct {
	*mock.Call
}

// ClearUserRefreshTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) ClearUserRefreshTokenHash(ctx interface{}, id interface{}) *Querier_ClearUserRefreshTokenHash_Call {
	return &Querier_ClearUserRefreshTokenHash_Call{Call: _e.mock.On("ClearUserRefreshTokenHash", ctx, id)}
}

func (_c *Querier_ClearUserRefreshTokenHash_Call) Run(run func(ctx context.Context, id string)) *Querier_ClearUserRefreshTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_ClearUserRefreshTokenHash_Call) Return(_a0 error) *Querier_ClearUserRefreshTokenHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_ClearUserRefreshTokenHash_Call) RunAndReturn(run func(context.Context, string) error) *Querier_ClearUserRefreshTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// ConsumeEmailLoginCode provides a mock function with given fields: ctx, id
func (_m *Querier) ConsumeEmailLoginCode(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeEmailLoginCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_ConsumeEmailLoginCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeEmailLoginCode'
type Querier_ConsumeEmailLoginCode_Call struct {
	*mock.Call
}

// ConsumeEmailLoginCode is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) ConsumeEmailLoginCode(ctx interface{}, id interface{}) *Querier_ConsumeEmailLoginCode_Call {
	return &Querier_ConsumeEmailLoginCode_Call{Call: _e.mock.On("ConsumeEmailLoginCode", ctx, id)}
}

func (_c *Querier_ConsumeEmailLoginCode_Call) Run(run func(ctx context.Context, id string)) *Querier_ConsumeEmailLoginCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_ConsumeEmailLoginCode_Call) Return(_a0 error) *Querier_ConsumeEmailLoginCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_ConsumeEmailLoginCode_Call) RunAndReturn(run func(context.Context, string) error) *Querier_ConsumeEmailLoginCode_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEmailLoginCode provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateEmailLoginCode(ctx context.Context, arg sqlcgen.CreateEmailLoginCodeParams) (sqlcgen.EmailLoginCode, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmailLoginCode")
	}

	var r0 sqlcgen.EmailLoginCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateEmailLoginCodeParams) (sqlcgen.EmailLoginCode, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateEmailLoginCodeParams) sqlcgen.EmailLoginCode); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.EmailLoginCode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateEmailLoginCodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateEmailLoginCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmailLoginCode'
type Querier_CreateEmailLoginCode_Call struct {
	*mock.Call
}

// CreateEmailLoginCode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.CreateEmailLoginCodeParams
func (_e *Querier_Expecter) CreateEmailLoginCode(ctx interface{}, arg interface{}) *Querier_CreateEmailLoginCode_Call {
	return &Querier_CreateEmailLoginCode_Call{Call: _e.mock.On("CreateEmailLoginCode", ctx, arg)}
}

func (_c *Querier_CreateEmailLoginCode_Call) Run(run func(ctx context.Context, arg sqlcgen.CreateEmailLoginCodeParams)) *Querier_CreateEmailLoginCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.CreateEmailLoginCodeParams))
	})
	return _c
}

func (_c *Querier_CreateEmailLoginCode_Call) Return(_a0 sqlcgen.EmailLoginCode, _a1 error) *Querier_CreateEmailLoginCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateEmailLoginCode_Call) RunAndReturn(run func(context.Context, sqlcgen.CreateEmailLoginCodeParams) (sqlcgen.EmailLoginCode, error)) *Querier_CreateEmailLoginCode_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateUser(ctx context.Context, arg sqlcgen.CreateUserParams) (sqlcgen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateUserParams) (sqlcgen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateUserParams) sqlcgen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Querier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.CreateUserParams
func (_e *Querier_Expecter) CreateUser(ctx interface{}, arg interface{}) *Querier_CreateUser_Call {
	return &Querier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *Querier_CreateUser_Call) Run(run func(ctx context.Context, arg sqlcgen.CreateUserParams)) *Querier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.CreateUserParams))
	})
	return _c
}

func (_c *Querier_CreateUser_Call) Return(_a0 sqlcgen.User, _a1 error) *Querier_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateUser_Call) RunAndReturn(run func(context.Context, sqlcgen.CreateUserParams) (sqlcgen.User, error)) *Querier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastEmailLoginCode provides a mock function with given fields: ctx, email
func (_m *Querier) GetLastEmailLoginCode(ctx context.Context, email string) (sqlcgen.EmailLoginCode, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetLastEmailLoginCode")
	}

	var r0 sqlcgen.EmailLoginCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.EmailLoginCode, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.EmailLoginCode); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlcgen.EmailLoginCode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetLastEmailLoginCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastEmailLoginCode'
type Querier_GetLastEmailLoginCode_Call struct {
	*mock.Call
}

// GetLastEmailLoginCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Querier_Expecter) GetLastEmailLoginCode(ctx interface{}, email interface{}) *Querier_GetLastEmailLoginCode_Call {
	return &Querier_GetLastEmailLoginCode_Call{Call: _e.mock.On("GetLastEmailLoginCode", ctx, email)}
}

func (_c *Querier_GetLastEmailLoginCode_Call) Run(run func(ctx context.Context, email string)) *Querier_GetLastEmailLoginCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetLastEmailLoginCode_Call) Return(_a0 sqlcgen.EmailLoginCode, _a1 error) *Querier_GetLastEmailLoginCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetLastEmailLoginCode_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.EmailLoginCode, error)) *Querier_GetLastEmailLoginCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingEmailLoginCode provides a mock function with given fields: ctx, email
func (_m *Querier) GetPendingEmailLoginCode(ctx context.Context, email string) (sqlcgen.EmailLoginCode, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingEmailLoginCode")
	}

	var r0 sqlcgen.EmailLoginCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.EmailLoginCode, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.EmailLoginCode); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlcgen.EmailLoginCode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetPendingEmailLoginCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingEmailLoginCode'
type Querier_GetPendingEmailLoginCode_Call struct {
	*mock.Call
}

// GetPendingEmailLoginCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Querier_Expecter) GetPendingEmailLoginCode(ctx interface{}, email interface{}) *Querier_GetPendingEmailLoginCode_Call {
	return &Querier_GetPendingEmailLoginCode_Call{Call: _e.mock.On("GetPendingEmailLoginCode", ctx, email)}
}

func (_c *Querier_GetPendingEmailLoginCode_Call) Run(run func(ctx context.Context, email string)) *Querier_GetPendingEmailLoginCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetPendingEmailLoginCode_Call) Return(_a0 sqlcgen.EmailLoginCode, _a1 error) *Querier_GetPendingEmailLoginCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetPendingEmailLoginCode_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.EmailLoginCode, error)) *Querier_GetPendingEmailLoginCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *Querier) GetUserByID(ctx context.Context, id string) (sqlcgen.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Querier_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) GetUserByID(ctx interface{}, id interface{}) *Querier_GetUserByID_Call {
	return &Querier_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *Querier_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *Querier_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetUserByID_Call) Return(_a0 sqlcgen.User, _a1 error) *Querier_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.User, error)) *Querier_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByProviderID provides a mock function with given fields: ctx, arg
func (_m *Querier) GetUserByProviderID(ctx context.Context, arg sqlcgen.GetUserByProviderIDParams) (sqlcgen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByProviderID")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetUserByProviderIDParams) (sqlcgen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetUserByProviderIDParams) sqlcgen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.GetUserByProviderIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetUserByProviderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByProviderID'
type Querier_GetUserByProviderID_Call struct {
	*mock.Call
}

// GetUserByProviderID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.GetUserByProviderIDParams
func (_e *Querier_Expecter) GetUserByProviderID(ctx interface{}, arg interface{}) *Querier_GetUserByProviderID_Call {
	return &Querier_GetUserByProviderID_Call{Call: _e.mock.On("GetUserByProviderID", ctx, arg)}
}

func (_c *Querier_GetUserByProviderID_Call) Run(run func(ctx context.Context, arg sqlcgen.GetUserByProviderIDParams)) *Querier_GetUserByProviderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.GetUserByProviderIDParams))
	})
	return _c
}

func (_c *Querier_GetUserByProviderID_Call) Return(_a0 sqlcgen.User, _a1 error) *Querier_GetUserByProviderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetUserByProviderID_Call) RunAndReturn(run func(context.Context, sqlcgen.GetUserByProviderIDParams) (sqlcgen.User, error)) *Querier_GetUserByProviderID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementEmailLoginCodeAttempts provides a mock function with given fields: ctx, id
func (_m *Querier) IncrementEmailLoginCodeAttempts(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementEmailLoginCodeAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_IncrementEmailLoginCodeAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementEmailLoginCodeAttempts'
type Querier_IncrementEmailLoginCodeAttempts_Call struct {
	*mock.Call
}

// IncrementEmailLoginCodeAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) IncrementEmailLoginCodeAttempts(ctx interface{}, id interface{}) *Querier_IncrementEmailLoginCodeAttempts_Call {
	return &Querier_IncrementEmailLoginCodeAttempts_Call{Call: _e.mock.On("IncrementEmailLoginCodeAttempts", ctx, id)}
}

func (_c *Querier_IncrementEmailLoginCodeAttempts_Call) Run(run func(ctx context.Context, id string)) *Querier_IncrementEmailLoginCodeAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_IncrementEmailLoginCodeAttempts_Call) Return(_a0 error) *Querier_IncrementEmailLoginCodeAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_IncrementEmailLoginCodeAttempts_Call) RunAndReturn(run func(context.Context, string) error) *Querier_IncrementEmailLoginCodeAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRefreshTokenHash provides a mock function with given fields: ctx, arg
func (_m *Querier) SetUserRefreshTokenHash(ctx context.Context, arg sqlcgen.SetUserRefreshTokenHashParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRefreshTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.SetUserRefreshTokenHashParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_SetUserRefreshTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRefreshTokenHash'
type Querier_SetUserRefreshTokenHash_Call struct {
	*mock.Call
}

// SetUserRefreshTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.SetUserRefreshTokenHashParams
func (_e *Querier_Expecter) SetUserRefreshTokenHash(ctx interface{}, arg interface{}) *Querier_SetUserRefreshTokenHash_Call {
	return &Querier_SetUserRefreshTokenHash_Call{Call: _e.mock.On("SetUserRefreshTokenHash", ctx, arg)}
}

func (_c *Querier_SetUserRefreshTokenHash_Call) Run(run func(ctx context.Context, arg sqlcgen.SetUserRefreshTokenHashParams)) *Querier_SetUserRefreshTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.SetUserRefreshTokenHashParams))
	})
	return _c
}

func (_c *Querier_SetUserRefreshTokenHash_Call) Return(_a0 error) *Querier_SetUserRefreshTokenHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_SetUserRefreshTokenHash_Call) RunAndReturn(run func(context.Context, sqlcgen.SetUserRefreshTokenHashParams) error) *Querier_SetUserRefreshTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateUserProfile(ctx context.Context, arg sqlcgen.UpdateUserProfileParams) (sqlcgen.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 sqlcgen.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateUserProfileParams) (sqlcgen.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateUserProfileParams) sqlcgen.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.UpdateUserProfileParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type Querier_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.UpdateUserProfileParams
func (_e *Querier_Expecter) UpdateUserProfile(ctx interface{}, arg interface{}) *Querier_UpdateUserProfile_Call {
	return &Querier_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, arg)}
}

func (_c *Querier_UpdateUserProfile_Call) Run(run func(ctx context.Context, arg sqlcgen.UpdateUserProfileParams)) *Querier_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.UpdateUserProfileParams))
	})
	return _c
}

func (_c *Querier_UpdateUserProfile_Call) Return(_a0 sqlcgen.User, _a1 error) *Querier_UpdateUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_UpdateUserProfile_Call) RunAndReturn(run func(context.Context, sqlcgen.UpdateUserProfileParams) (sqlcgen.User, error)) *Querier_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
