// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Categorizer is an autogenerated mock type for the Categorizer type
type Categorizer struct {
	mock.Mock
}

type Categorizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Categorizer) EXPECT() *Categorizer_Expecter {
	return &Categorizer_Expecter{mock: &_m.Mock}
}

// GenerateCompletionResponse provides a mock function with given fields: ctx, promptTemplate, variables
func (_m *Categorizer) GenerateCompletionResponse(ctx context.Context, promptTemplate string, variables map[string]string) (string, error) {
	ret := _m.Called(ctx, promptTemplate, variables)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCompletionResponse")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (string, error)); ok {
		return rf(ctx, promptTemplate, variables)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) string); ok {
		r0 = rf(ctx, promptTemplate, variables)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, promptTemplate, variables)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Categorizer_GenerateCompletionResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCompletionResponse'
type Categorizer_GenerateCompletionResponse_Call struct {
	*mock.Call
}

// GenerateCompletionResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - promptTemplate string
//   - variables map[string]string
func (_e *Categorizer_Expecter) GenerateCompletionResponse(ctx interface{}, promptTemplate interface{}, variables interface{}) *Categorizer_GenerateCompletionResponse_Call {
	return &Categorizer_GenerateCompletionResponse_Call{Call: _e.mock.On("GenerateCompletionResponse", ctx, promptTemplate, variables)}
}

func (_c *Categorizer_GenerateCompletionResponse_Call) Run(run func(ctx context.Context, promptTemplate string, variables map[string]string)) *Categorizer_GenerateCompletionResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *Categorizer_GenerateCompletionResponse_Call) Return(_a0 string, _a1 error) *Categorizer_GenerateCompletionResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Categorizer_GenerateCompletionResponse_Call) RunAndReturn(run func(context.Context, string, map[string]string) (string, error)) *Categorizer_GenerateCompletionResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategorizer creates a new instance of Categorizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategorizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Categorizer {
	mock := &Categorizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
