// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	places "github.com/juanobrach/zig-zag/go-be/internal/places"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// GetPlaceDetails provides a mock function with given fields: ctx, placeID
func (_m *Provider) GetPlaceDetails(ctx context.Context, placeID string) (places.PlaceData, error) {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlaceDetails")
	}

	var r0 places.PlaceData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (places.PlaceData, error)); ok {
		return rf(ctx, placeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) places.PlaceData); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Get(0).(places.PlaceData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, placeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_GetPlaceDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaceDetails'
type Provider_GetPlaceDetails_Call struct {
	*mock.Call
}

// GetPlaceDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *Provider_Expecter) GetPlaceDetails(ctx interface{}, placeID interface{}) *Provider_GetPlaceDetails_Call {
	return &Provider_GetPlaceDetails_Call{Call: _e.mock.On("GetPlaceDetails", ctx, placeID)}
}

func (_c *Provider_GetPlaceDetails_Call) Run(run func(ctx context.Context, placeID string)) *Provider_GetPlaceDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Provider_GetPlaceDetails_Call) Return(_a0 places.PlaceData, _a1 error) *Provider_GetPlaceDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_GetPlaceDetails_Call) RunAndReturn(run func(context.Context, string) (places.PlaceData, error)) *Provider_GetPlaceDetails_Call {
	_c.Call.Return(run)
	return _c
}

// SearchNearby provides a mock function with given fields: ctx, params
func (_m *Provider) SearchNearby(ctx context.Context, params places.SearchNearbyParams) ([]places.PlaceData, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchNearby")
	}

	var r0 []places.PlaceData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, places.SearchNearbyParams) ([]places.PlaceData, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, places.SearchNearbyParams) []places.PlaceData); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]places.PlaceData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, places.SearchNearbyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_SearchNearby_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchNearby'
type Provider_SearchNearby_Call struct {
	*mock.Call
}

// SearchNearby is a helper method to define mock.On call
//   - ctx context.Context
//   - params places.SearchNearbyParams
func (_e *Provider_Expecter) SearchNearby(ctx interface{}, params interface{}) *Provider_SearchNearby_Call {
	return &Provider_SearchNearby_Call{Call: _e.mock.On("SearchNearby", ctx, params)}
}

func (_c *Provider_SearchNearby_Call) Run(run func(ctx context.Context, params places.SearchNearbyParams)) *Provider_SearchNearby_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(places.SearchNearbyParams))
	})
	return _c
}

func (_c *Provider_SearchNearby_Call) Return(_a0 []places.PlaceData, _a1 error) *Provider_SearchNearby_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_SearchNearby_Call) RunAndReturn(run func(context.Context, places.SearchNearbyParams) ([]places.PlaceData, error)) *Provider_SearchNearby_Call {
	_c.Call.Return(run)
	return _c
}

// SearchText provides a mock function with given fields: ctx, params
func (_m *Provider) SearchText(ctx context.Context, params places.SearchTextParams) ([]places.PlaceData, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchText")
	}

	var r0 []places.PlaceData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, places.SearchTextParams) ([]places.PlaceData, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, places.SearchTextParams) []places.PlaceData); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]places.PlaceData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, places.SearchTextParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Provider_SearchText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchText'
type Provider_SearchText_Call struct {
	*mock.Call
}

// SearchText is a helper method to define mock.On call
//   - ctx context.Context
//   - params places.SearchTextParams
func (_e *Provider_Expecter) SearchText(ctx interface{}, params interface{}) *Provider_SearchText_Call {
	return &Provider_SearchText_Call{Call: _e.mock.On("SearchText", ctx, params)}
}

func (_c *Provider_SearchText_Call) Run(run func(ctx context.Context, params places.SearchTextParams)) *Provider_SearchText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(places.SearchTextParams))
	})
	return _c
}

func (_c *Provider_SearchText_Call) Return(_a0 []places.PlaceData, _a1 error) *Provider_SearchText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Provider_SearchText_Call) RunAndReturn(run func(context.Context, places.SearchTextParams) ([]places.PlaceData, error)) *Provider_SearchText_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
