// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EmbeddingSaver is an autogenerated mock type for the EmbeddingSaver type
type EmbeddingSaver struct {
	mock.Mock
}

type EmbeddingSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *EmbeddingSaver) EXPECT() *EmbeddingSaver_Expecter {
	return &EmbeddingSaver_Expecter{mock: &_m.Mock}
}

// AddActivityToVectorStore provides a mock function with given fields: ctx, id, name, description, activityType, metadataJSON
func (_m *EmbeddingSaver) AddActivityToVectorStore(ctx context.Context, id string, name string, description *string, activityType *string, metadataJSON []byte) error {
	ret := _m.Called(ctx, id, name, description, activityType, metadataJSON)

	if len(ret) == 0 {
		panic("no return value specified for AddActivityToVectorStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, *string, []byte) error); ok {
		r0 = rf(ctx, id, name, description, activityType, metadataJSON)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmbeddingSaver_AddActivityToVectorStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddActivityToVectorStore'
type EmbeddingSaver_AddActivityToVectorStore_Call struct {
	*mock.Call
}

// AddActivityToVectorStore is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - description *string
//   - activityType *string
//   - metadataJSON []byte
func (_e *EmbeddingSaver_Expecter) AddActivityToVectorStore(ctx interface{}, id interface{}, name interface{}, description interface{}, activityType interface{}, metadataJSON interface{}) *EmbeddingSaver_AddActivityToVectorStore_Call {
	return &EmbeddingSaver_AddActivityToVectorStore_Call{Call: _e.mock.On("AddActivityToVectorStore", ctx, id, name, description, activityType, metadataJSON)}
}

func (_c *EmbeddingSaver_AddActivityToVectorStore_Call) Run(run func(ctx context.Context, id string, name string, description *string, activityType *string, metadataJSON []byte)) *EmbeddingSaver_AddActivityToVectorStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string), args[4].(*string), args[5].([]byte))
	})
	return _c
}

func (_c *EmbeddingSaver_AddActivityToVectorStore_Call) Return(_a0 error) *EmbeddingSaver_AddActivityToVectorStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EmbeddingSaver_AddActivityToVectorStore_Call) RunAndReturn(run func(context.Context, string, string, *string, *string, []byte) error) *EmbeddingSaver_AddActivityToVectorStore_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmbeddingSaver creates a new instance of EmbeddingSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbeddingSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmbeddingSaver {
	mock := &EmbeddingSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
