// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	places "github.com/juanobrach/zig-zag/go-be/internal/places"
	mock "github.com/stretchr/testify/mock"
)

// ActivityCreator is an autogenerated mock type for the ActivityCreator type
type ActivityCreator struct {
	mock.Mock
}

type ActivityCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityCreator) EXPECT() *ActivityCreator_Expecter {
	return &ActivityCreator_Expecter{mock: &_m.Mock}
}

// CreateFromDraft provides a mock function with given fields: ctx, draft
func (_m *ActivityCreator) CreateFromDraft(ctx context.Context, draft places.ActivityDraft) (string, error) {
	ret := _m.Called(ctx, draft)

	if len(ret) == 0 {
		panic("no return value specified for CreateFromDraft")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, places.ActivityDraft) (string, error)); ok {
		return rf(ctx, draft)
	}
	if rf, ok := ret.Get(0).(func(context.Context, places.ActivityDraft) string); ok {
		r0 = rf(ctx, draft)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, places.ActivityDraft) error); ok {
		r1 = rf(ctx, draft)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityCreator_CreateFromDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFromDraft'
type ActivityCreator_CreateFromDraft_Call struct {
	*mock.Call
}

// CreateFromDraft is a helper method to define mock.On call
//   - ctx context.Context
//   - draft places.ActivityDraft
func (_e *ActivityCreator_Expecter) CreateFromDraft(ctx interface{}, draft interface{}) *ActivityCreator_CreateFromDraft_Call {
	return &ActivityCreator_CreateFromDraft_Call{Call: _e.mock.On("CreateFromDraft", ctx, draft)}
}

func (_c *ActivityCreator_CreateFromDraft_Call) Run(run func(ctx context.Context, draft places.ActivityDraft)) *ActivityCreator_CreateFromDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(places.ActivityDraft))
	})
	return _c
}

func (_c *ActivityCreator_CreateFromDraft_Call) Return(id string, err error) *ActivityCreator_CreateFromDraft_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *ActivityCreator_CreateFromDraft_Call) RunAndReturn(run func(context.Context, places.ActivityDraft) (string, error)) *ActivityCreator_CreateFromDraft_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityCreator creates a new instance of ActivityCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityCreator {
	mock := &ActivityCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
