// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// CreateKnownActivityType provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateKnownActivityType(ctx context.Context, arg sqlcgen.CreateKnownActivityTypeParams) (sqlcgen.KnownActivityType, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateKnownActivityType")
	}

	var r0 sqlcgen.KnownActivityType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateKnownActivityTypeParams) (sqlcgen.KnownActivityType, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateKnownActivityTypeParams) sqlcgen.KnownActivityType); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.KnownActivityType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateKnownActivityTypeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateKnownActivityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKnownActivityType'
type Querier_CreateKnownActivityType_Call struct {
	*mock.Call
}

// CreateKnownActivityType is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.CreateKnownActivityTypeParams
func (_e *Querier_Expecter) CreateKnownActivityType(ctx interface{}, arg interface{}) *Querier_CreateKnownActivityType_Call {
	return &Querier_CreateKnownActivityType_Call{Call: _e.mock.On("CreateKnownActivityType", ctx, arg)}
}

func (_c *Querier_CreateKnownActivityType_Call) Run(run func(ctx context.Context, arg sqlcgen.CreateKnownActivityTypeParams)) *Querier_CreateKnownActivityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.CreateKnownActivityTypeParams))
	})
	return _c
}

func (_c *Querier_CreateKnownActivityType_Call) Return(_a0 sqlcgen.KnownActivityType, _a1 error) *Querier_CreateKnownActivityType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateKnownActivityType_Call) RunAndReturn(run func(context.Context, sqlcgen.CreateKnownActivityTypeParams) (sqlcgen.KnownActivityType, error)) *Querier_CreateKnownActivityType_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSource provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateSource(ctx context.Context, arg sqlcgen.CreateSourceParams) (sqlcgen.Source, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSource")
	}

	var r0 sqlcgen.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateSourceParams) (sqlcgen.Source, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CreateSourceParams) sqlcgen.Source); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlcgen.Source)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CreateSourceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CreateSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSource'
type Querier_CreateSource_Call struct {
	*mock.Call
}

// CreateSource is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.CreateSourceParams
func (_e *Querier_Expecter) CreateSource(ctx interface{}, arg interface{}) *Querier_CreateSource_Call {
	return &Querier_CreateSource_Call{Call: _e.mock.On("CreateSource", ctx, arg)}
}

func (_c *Querier_CreateSource_Call) Run(run func(ctx context.Context, arg sqlcgen.CreateSourceParams)) *Querier_CreateSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.CreateSourceParams))
	})
	return _c
}

func (_c *Querier_CreateSource_Call) Return(_a0 sqlcgen.Source, _a1 error) *Querier_CreateSource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CreateSource_Call) RunAndReturn(run func(context.Context, sqlcgen.CreateSourceParams) (sqlcgen.Source, error)) *Querier_CreateSource_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityBySourceAndExternalID provides a mock function with given fields: ctx, arg
func (_m *Querier) GetActivityBySourceAndExternalID(ctx context.Context, arg sqlcgen.GetActivityBySourceAndExternalIDParams) (string, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityBySourceAndExternalID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetActivityBySourceAndExternalIDParams) (string, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.GetActivityBySourceAndExternalIDParams) string); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.GetActivityBySourceAndExternalIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetActivityBySourceAndExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityBySourceAndExternalID'
type Querier_GetActivityBySourceAndExternalID_Call struct {
	*mock.Call
}

// GetActivityBySourceAndExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.GetActivityBySourceAndExternalIDParams
func (_e *Querier_Expecter) GetActivityBySourceAndExternalID(ctx interface{}, arg interface{}) *Querier_GetActivityBySourceAndExternalID_Call {
	return &Querier_GetActivityBySourceAndExternalID_Call{Call: _e.mock.On("GetActivityBySourceAndExternalID", ctx, arg)}
}

func (_c *Querier_GetActivityBySourceAndExternalID_Call) Run(run func(ctx context.Context, arg sqlcgen.GetActivityBySourceAndExternalIDParams)) *Querier_GetActivityBySourceAndExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.GetActivityBySourceAndExternalIDParams))
	})
	return _c
}

func (_c *Querier_GetActivityBySourceAndExternalID_Call) Return(_a0 string, _a1 error) *Querier_GetActivityBySourceAndExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetActivityBySourceAndExternalID_Call) RunAndReturn(run func(context.Context, sqlcgen.GetActivityBySourceAndExternalIDParams) (string, error)) *Querier_GetActivityBySourceAndExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetKnownActivityTypeByName provides a mock function with given fields: ctx, name
func (_m *Querier) GetKnownActivityTypeByName(ctx context.Context, name string) (sqlcgen.KnownActivityType, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetKnownActivityTypeByName")
	}

	var r0 sqlcgen.KnownActivityType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.KnownActivityType, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.KnownActivityType); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(sqlcgen.KnownActivityType)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetKnownActivityTypeByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKnownActivityTypeByName'
type Querier_GetKnownActivityTypeByName_Call struct {
	*mock.Call
}

// GetKnownActivityTypeByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Querier_Expecter) GetKnownActivityTypeByName(ctx interface{}, name interface{}) *Querier_GetKnownActivityTypeByName_Call {
	return &Querier_GetKnownActivityTypeByName_Call{Call: _e.mock.On("GetKnownActivityTypeByName", ctx, name)}
}

func (_c *Querier_GetKnownActivityTypeByName_Call) Run(run func(ctx context.Context, name string)) *Querier_GetKnownActivityTypeByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetKnownActivityTypeByName_Call) Return(_a0 sqlcgen.KnownActivityType, _a1 error) *Querier_GetKnownActivityTypeByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetKnownActivityTypeByName_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.KnownActivityType, error)) *Querier_GetKnownActivityTypeByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceByName provides a mock function with given fields: ctx, name
func (_m *Querier) GetSourceByName(ctx context.Context, name string) (sqlcgen.Source, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSourceByName")
	}

	var r0 sqlcgen.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.Source, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.Source); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(sqlcgen.Source)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetSourceByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceByName'
type Querier_GetSourceByName_Call struct {
	*mock.Call
}

// GetSourceByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Querier_Expecter) GetSourceByName(ctx interface{}, name interface{}) *Querier_GetSourceByName_Call {
	return &Querier_GetSourceByName_Call{Call: _e.mock.On("GetSourceByName", ctx, name)}
}

func (_c *Querier_GetSourceByName_Call) Run(run func(ctx context.Context, name string)) *Querier_GetSourceByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetSourceByName_Call) Return(_a0 sqlcgen.Source, _a1 error) *Querier_GetSourceByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetSourceByName_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.Source, error)) *Querier_GetSourceByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateKnownActivityType provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateKnownActivityType(ctx context.Context, arg sqlcgen.UpdateKnownActivityTypeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKnownActivityType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateKnownActivityTypeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateKnownActivityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateKnownActivityType'
type Querier_UpdateKnownActivityType_Call struct {
	*mock.Call
}

// UpdateKnownActivityType is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.UpdateKnownActivityTypeParams
func (_e *Querier_Expecter) UpdateKnownActivityType(ctx interface{}, arg interface{}) *Querier_UpdateKnownActivityType_Call {
	return &Querier_UpdateKnownActivityType_Call{Call: _e.mock.On("UpdateKnownActivityType", ctx, arg)}
}

func (_c *Querier_UpdateKnownActivityType_Call) Run(run func(ctx context.Context, arg sqlcgen.UpdateKnownActivityTypeParams)) *Querier_UpdateKnownActivityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.UpdateKnownActivityTypeParams))
	})
	return _c
}

func (_c *Querier_UpdateKnownActivityType_Call) Return(_a0 error) *Querier_UpdateKnownActivityType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateKnownActivityType_Call) RunAndReturn(run func(context.Context, sqlcgen.UpdateKnownActivityTypeParams) error) *Querier_UpdateKnownActivityType_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
