// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ImageGenerator is an autogenerated mock type for the ImageGenerator type
type ImageGenerator struct {
	mock.Mock
}

type ImageGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageGenerator) EXPECT() *ImageGenerator_Expecter {
	return &ImageGenerator_Expecter{mock: &_m.Mock}
}

// GenerateImage provides a mock function with given fields: ctx, prompt, size, bypass
func (_m *ImageGenerator) GenerateImage(ctx context.Context, prompt string, size string, bypass bool) string {
	ret := _m.Called(ctx, prompt, size, bypass)

	if len(ret) == 0 {
		panic("no return value specified for GenerateImage")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) string); ok {
		r0 = rf(ctx, prompt, size, bypass)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ImageGenerator_GenerateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateImage'
type ImageGenerator_GenerateImage_Call struct {
	*mock.Call
}

// GenerateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - size string
//   - bypass bool
func (_e *ImageGenerator_Expecter) GenerateImage(ctx interface{}, prompt interface{}, size interface{}, bypass interface{}) *ImageGenerator_GenerateImage_Call {
	return &ImageGenerator_GenerateImage_Call{Call: _e.mock.On("GenerateImage", ctx, prompt, size, bypass)}
}

func (_c *ImageGenerator_GenerateImage_Call) Run(run func(ctx context.Context, prompt string, size string, bypass bool)) *ImageGenerator_GenerateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *ImageGenerator_GenerateImage_Call) Return(_a0 string) *ImageGenerator_GenerateImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageGenerator_GenerateImage_Call) RunAndReturn(run func(context.Context, string, string, bool) string) *ImageGenerator_GenerateImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewImageGenerator creates a new instance of ImageGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageGenerator {
	mock := &ImageGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
