// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
	mock "github.com/stretchr/testify/mock"
)

// LocationQuerier is an autogenerated mock type for the LocationQuerier type
type LocationQuerier struct {
	mock.Mock
}

type LocationQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *LocationQuerier) EXPECT() *LocationQuerier_Expecter {
	return &LocationQuerier_Expecter{mock: &_m.Mock}
}

// ListToursNearCategory provides a mock function with given fields: ctx, arg
func (_m *LocationQuerier) ListToursNearCategory(ctx context.Context, arg sqlcgen.ListToursNearCategoryParams) ([]sqlcgen.Tour, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListToursNearCategory")
	}

	var r0 []sqlcgen.Tour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.ListToursNearCategoryParams) ([]sqlcgen.Tour, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.ListToursNearCategoryParams) []sqlcgen.Tour); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.Tour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.ListToursNearCategoryParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LocationQuerier_ListToursNearCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListToursNearCategory'
type LocationQuerier_ListToursNearCategory_Call struct {
	*mock.Call
}

// ListToursNearCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.ListToursNearCategoryParams
func (_e *LocationQuerier_Expecter) ListToursNearCategory(ctx interface{}, arg interface{}) *LocationQuerier_ListToursNearCategory_Call {
	return &LocationQuerier_ListToursNearCategory_Call{Call: _e.mock.On("ListToursNearCategory", ctx, arg)}
}

func (_c *LocationQuerier_ListToursNearCategory_Call) Run(run func(ctx context.Context, arg sqlcgen.ListToursNearCategoryParams)) *LocationQuerier_ListToursNearCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.ListToursNearCategoryParams))
	})
	return _c
}

func (_c *LocationQuerier_ListToursNearCategory_Call) Return(_a0 []sqlcgen.Tour, _a1 error) *LocationQuerier_ListToursNearCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LocationQuerier_ListToursNearCategory_Call) RunAndReturn(run func(context.Context, sqlcgen.ListToursNearCategoryParams) ([]sqlcgen.Tour, error)) *LocationQuerier_ListToursNearCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewLocationQuerier creates a new instance of LocationQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocationQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocationQuerier {
	mock := &LocationQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
