// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	tours "github.com/juanobrach/zig-zag/go-be/internal/tours"
	mock "github.com/stretchr/testify/mock"
)

// ActivityFinder is an autogenerated mock type for the ActivityFinder type
type ActivityFinder struct {
	mock.Mock
}

type ActivityFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityFinder) EXPECT() *ActivityFinder_Expecter {
	return &ActivityFinder_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx, latitude, longitude, radiusMeters, limit, types
func (_m *ActivityFinder) FindAll(ctx context.Context, latitude string, longitude string, radiusMeters float64, limit int, types []string) ([]tours.CandidateActivity, error) {
	ret := _m.Called(ctx, latitude, longitude, radiusMeters, limit, types)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []tours.CandidateActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, int, []string) ([]tours.CandidateActivity, error)); ok {
		return rf(ctx, latitude, longitude, radiusMeters, limit, types)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, int, []string) []tours.CandidateActivity); ok {
		r0 = rf(ctx, latitude, longitude, radiusMeters, limit, types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tours.CandidateActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, float64, int, []string) error); ok {
		r1 = rf(ctx, latitude, longitude, radiusMeters, limit, types)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActivityFinder_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type ActivityFinder_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - latitude string
//   - longitude string
//   - radiusMeters float64
//   - limit int
//   - types []string
func (_e *ActivityFinder_Expecter) FindAll(ctx interface{}, latitude interface{}, longitude interface{}, radiusMeters interface{}, limit interface{}, types interface{}) *ActivityFinder_FindAll_Call {
	return &ActivityFinder_FindAll_Call{Call: _e.mock.On("FindAll", ctx, latitude, longitude, radiusMeters, limit, types)}
}

func (_c *ActivityFinder_FindAll_Call) Run(run func(ctx context.Context, latitude string, longitude string, radiusMeters float64, limit int, types []string)) *ActivityFinder_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64), args[4].(int), args[5].([]string))
	})
	return _c
}

func (_c *ActivityFinder_FindAll_Call) Return(_a0 []tours.CandidateActivity, _a1 error) *ActivityFinder_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActivityFinder_FindAll_Call) RunAndReturn(run func(context.Context, string, string, float64, int, []string) ([]tours.CandidateActivity, error)) *ActivityFinder_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityFinder creates a new instance of ActivityFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityFinder {
	mock := &ActivityFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
