// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Chatter is an autogenerated mock type for the Chatter type
type Chatter struct {
	mock.Mock
}

type Chatter_Expecter struct {
	mock *mock.Mock
}

func (_m *Chatter) EXPECT() *Chatter_Expecter {
	return &Chatter_Expecter{mock: &_m.Mock}
}

// GenerateChatResponse provides a mock function with given fields: ctx, systemPromptTemplate, userPromptTemplate, variables
func (_m *Chatter) GenerateChatResponse(ctx context.Context, systemPromptTemplate string, userPromptTemplate string, variables map[string]string) (string, error) {
	ret := _m.Called(ctx, systemPromptTemplate, userPromptTemplate, variables)

	if len(ret) == 0 {
		panic("no return value specified for GenerateChatResponse")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) (string, error)); ok {
		return rf(ctx, systemPromptTemplate, userPromptTemplate, variables)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) string); ok {
		r0 = rf(ctx, systemPromptTemplate, userPromptTemplate, variables)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]string) error); ok {
		r1 = rf(ctx, systemPromptTemplate, userPromptTemplate, variables)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Chatter_GenerateChatResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateChatResponse'
type Chatter_GenerateChatResponse_Call struct {
	*mock.Call
}

// GenerateChatResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - systemPromptTemplate string
//   - userPromptTemplate string
//   - variables map[string]string
func (_e *Chatter_Expecter) GenerateChatResponse(ctx interface{}, systemPromptTemplate interface{}, userPromptTemplate interface{}, variables interface{}) *Chatter_GenerateChatResponse_Call {
	return &Chatter_GenerateChatResponse_Call{Call: _e.mock.On("GenerateChatResponse", ctx, systemPromptTemplate, userPromptTemplate, variables)}
}

func (_c *Chatter_GenerateChatResponse_Call) Run(run func(ctx context.Context, systemPromptTemplate string, userPromptTemplate string, variables map[string]string)) *Chatter_GenerateChatResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *Chatter_GenerateChatResponse_Call) Return(_a0 string, _a1 error) *Chatter_GenerateChatResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Chatter_GenerateChatResponse_Call) RunAndReturn(run func(context.Context, string, string, map[string]string) (string, error)) *Chatter_GenerateChatResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewChatter creates a new instance of Chatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Chatter {
	mock := &Chatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
