// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlcgen "github.com/juanobrach/zig-zag/go-be/internal/db/sqlcgen"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// CountToursByOwner provides a mock function with given fields: ctx, arg
func (_m *Querier) CountToursByOwner(ctx context.Context, arg sqlcgen.CountToursByOwnerParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CountToursByOwner")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CountToursByOwnerParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.CountToursByOwnerParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.CountToursByOwnerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_CountToursByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountToursByOwner'
type Querier_CountToursByOwner_Call struct {
	*mock.Call
}

// CountToursByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.CountToursByOwnerParams
func (_e *Querier_Expecter) CountToursByOwner(ctx interface{}, arg interface{}) *Querier_CountToursByOwner_Call {
	return &Querier_CountToursByOwner_Call{Call: _e.mock.On("CountToursByOwner", ctx, arg)}
}

func (_c *Querier_CountToursByOwner_Call) Run(run func(ctx context.Context, arg sqlcgen.CountToursByOwnerParams)) *Querier_CountToursByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.CountToursByOwnerParams))
	})
	return _c
}

func (_c *Querier_CountToursByOwner_Call) Return(_a0 int64, _a1 error) *Querier_CountToursByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_CountToursByOwner_Call) RunAndReturn(run func(context.Context, sqlcgen.CountToursByOwnerParams) (int64, error)) *Querier_CountToursByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTour provides a mock function with given fields: ctx, id
func (_m *Querier) DeleteTour(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTour")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_DeleteTour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTour'
type Querier_DeleteTour_Call struct {
	*mock.Call
}

// DeleteTour is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) DeleteTour(ctx interface{}, id interface{}) *Querier_DeleteTour_Call {
	return &Querier_DeleteTour_Call{Call: _e.mock.On("DeleteTour", ctx, id)}
}

func (_c *Querier_DeleteTour_Call) Run(run func(ctx context.Context, id string)) *Querier_DeleteTour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_DeleteTour_Call) Return(_a0 error) *Querier_DeleteTour_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_DeleteTour_Call) RunAndReturn(run func(context.Context, string) error) *Querier_DeleteTour_Call {
	_c.Call.Return(run)
	return _c
}

// GetTour provides a mock function with given fields: ctx, id
func (_m *Querier) GetTour(ctx context.Context, id string) (sqlcgen.Tour, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTour")
	}

	var r0 sqlcgen.Tour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlcgen.Tour, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlcgen.Tour); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlcgen.Tour)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetTour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTour'
type Querier_GetTour_Call struct {
	*mock.Call
}

// GetTour is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) GetTour(ctx interface{}, id interface{}) *Querier_GetTour_Call {
	return &Querier_GetTour_Call{Call: _e.mock.On("GetTour", ctx, id)}
}

func (_c *Querier_GetTour_Call) Run(run func(ctx context.Context, id string)) *Querier_GetTour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetTour_Call) Return(_a0 sqlcgen.Tour, _a1 error) *Querier_GetTour_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetTour_Call) RunAndReturn(run func(context.Context, string) (sqlcgen.Tour, error)) *Querier_GetTour_Call {
	_c.Call.Return(run)
	return _c
}

// GetTourActivities provides a mock function with given fields: ctx, tourID
func (_m *Querier) GetTourActivities(ctx context.Context, tourID string) ([]sqlcgen.TourActivity, error) {
	ret := _m.Called(ctx, tourID)

	if len(ret) == 0 {
		panic("no return value specified for GetTourActivities")
	}

	var r0 []sqlcgen.TourActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]sqlcgen.TourActivity, error)); ok {
		return rf(ctx, tourID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []sqlcgen.TourActivity); ok {
		r0 = rf(ctx, tourID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.TourActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tourID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetTourActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTourActivities'
type Querier_GetTourActivities_Call struct {
	*mock.Call
}

// GetTourActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - tourID string
func (_e *Querier_Expecter) GetTourActivities(ctx interface{}, tourID interface{}) *Querier_GetTourActivities_Call {
	return &Querier_GetTourActivities_Call{Call: _e.mock.On("GetTourActivities", ctx, tourID)}
}

func (_c *Querier_GetTourActivities_Call) Run(run func(ctx context.Context, tourID string)) *Querier_GetTourActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetTourActivities_Call) Return(_a0 []sqlcgen.TourActivity, _a1 error) *Querier_GetTourActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetTourActivities_Call) RunAndReturn(run func(context.Context, string) ([]sqlcgen.TourActivity, error)) *Querier_GetTourActivities_Call {
	_c.Call.Return(run)
	return _c
}

// GetTourOwnerID provides a mock function with given fields: ctx, id
func (_m *Querier) GetTourOwnerID(ctx context.Context, id string) (*string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTourOwnerID")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_GetTourOwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTourOwnerID'
type Querier_GetTourOwnerID_Call struct {
	*mock.Call
}

// GetTourOwnerID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Querier_Expecter) GetTourOwnerID(ctx interface{}, id interface{}) *Querier_GetTourOwnerID_Call {
	return &Querier_GetTourOwnerID_Call{Call: _e.mock.On("GetTourOwnerID", ctx, id)}
}

func (_c *Querier_GetTourOwnerID_Call) Run(run func(ctx context.Context, id string)) *Querier_GetTourOwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Querier_GetTourOwnerID_Call) Return(_a0 *string, _a1 error) *Querier_GetTourOwnerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_GetTourOwnerID_Call) RunAndReturn(run func(context.Context, string) (*string, error)) *Querier_GetTourOwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// ListToursByOwner provides a mock function with given fields: ctx, arg
func (_m *Querier) ListToursByOwner(ctx context.Context, arg sqlcgen.ListToursByOwnerParams) ([]sqlcgen.Tour, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListToursByOwner")
	}

	var r0 []sqlcgen.Tour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.ListToursByOwnerParams) ([]sqlcgen.Tour, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.ListToursByOwnerParams) []sqlcgen.Tour); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.Tour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.ListToursByOwnerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListToursByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListToursByOwner'
type Querier_ListToursByOwner_Call struct {
	*mock.Call
}

// ListToursByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.ListToursByOwnerParams
func (_e *Querier_Expecter) ListToursByOwner(ctx interface{}, arg interface{}) *Querier_ListToursByOwner_Call {
	return &Querier_ListToursByOwner_Call{Call: _e.mock.On("ListToursByOwner", ctx, arg)}
}

func (_c *Querier_ListToursByOwner_Call) Run(run func(ctx context.Context, arg sqlcgen.ListToursByOwnerParams)) *Querier_ListToursByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.ListToursByOwnerParams))
	})
	return _c
}

func (_c *Querier_ListToursByOwner_Call) Return(_a0 []sqlcgen.Tour, _a1 error) *Querier_ListToursByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListToursByOwner_Call) RunAndReturn(run func(context.Context, sqlcgen.ListToursByOwnerParams) ([]sqlcgen.Tour, error)) *Querier_ListToursByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// ListToursNearCategory provides a mock function with given fields: ctx, arg
func (_m *Querier) ListToursNearCategory(ctx context.Context, arg sqlcgen.ListToursNearCategoryParams) ([]sqlcgen.Tour, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListToursNearCategory")
	}

	var r0 []sqlcgen.Tour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.ListToursNearCategoryParams) ([]sqlcgen.Tour, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.ListToursNearCategoryParams) []sqlcgen.Tour); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlcgen.Tour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlcgen.ListToursNearCategoryParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Querier_ListToursNearCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListToursNearCategory'
type Querier_ListToursNearCategory_Call struct {
	*mock.Call
}

// ListToursNearCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.ListToursNearCategoryParams
func (_e *Querier_Expecter) ListToursNearCategory(ctx interface{}, arg interface{}) *Querier_ListToursNearCategory_Call {
	return &Querier_ListToursNearCategory_Call{Call: _e.mock.On("ListToursNearCategory", ctx, arg)}
}

func (_c *Querier_ListToursNearCategory_Call) Run(run func(ctx context.Context, arg sqlcgen.ListToursNearCategoryParams)) *Querier_ListToursNearCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.ListToursNearCategoryParams))
	})
	return _c
}

func (_c *Querier_ListToursNearCategory_Call) Return(_a0 []sqlcgen.Tour, _a1 error) *Querier_ListToursNearCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Querier_ListToursNearCategory_Call) RunAndReturn(run func(context.Context, sqlcgen.ListToursNearCategoryParams) ([]sqlcgen.Tour, error)) *Querier_ListToursNearCategory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTourCoverImage provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateTourCoverImage(ctx context.Context, arg sqlcgen.UpdateTourCoverImageParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTourCoverImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateTourCoverImageParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateTourCoverImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTourCoverImage'
type Querier_UpdateTourCoverImage_Call struct {
	*mock.Call
}

// UpdateTourCoverImage is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.UpdateTourCoverImageParams
func (_e *Querier_Expecter) UpdateTourCoverImage(ctx interface{}, arg interface{}) *Querier_UpdateTourCoverImage_Call {
	return &Querier_UpdateTourCoverImage_Call{Call: _e.mock.On("UpdateTourCoverImage", ctx, arg)}
}

func (_c *Querier_UpdateTourCoverImage_Call) Run(run func(ctx context.Context, arg sqlcgen.UpdateTourCoverImageParams)) *Querier_UpdateTourCoverImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.UpdateTourCoverImageParams))
	})
	return _c
}

func (_c *Querier_UpdateTourCoverImage_Call) Return(_a0 error) *Querier_UpdateTourCoverImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateTourCoverImage_Call) RunAndReturn(run func(context.Context, sqlcgen.UpdateTourCoverImageParams) error) *Querier_UpdateTourCoverImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTourMetadata provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateTourMetadata(ctx context.Context, arg sqlcgen.UpdateTourMetadataParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTourMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlcgen.UpdateTourMetadataParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Querier_UpdateTourMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTourMetadata'
type Querier_UpdateTourMetadata_Call struct {
	*mock.Call
}

// UpdateTourMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg sqlcgen.UpdateTourMetadataParams
func (_e *Querier_Expecter) UpdateTourMetadata(ctx interface{}, arg interface{}) *Querier_UpdateTourMetadata_Call {
	return &Querier_UpdateTourMetadata_Call{Call: _e.mock.On("UpdateTourMetadata", ctx, arg)}
}

func (_c *Querier_UpdateTourMetadata_Call) Run(run func(ctx context.Context, arg sqlcgen.UpdateTourMetadataParams)) *Querier_UpdateTourMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sqlcgen.UpdateTourMetadataParams))
	})
	return _c
}

func (_c *Querier_UpdateTourMetadata_Call) Return(_a0 error) *Querier_UpdateTourMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Querier_UpdateTourMetadata_Call) RunAndReturn(run func(context.Context, sqlcgen.UpdateTourMetadataParams) error) *Querier_UpdateTourMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
